<script type="text/javascript">
    $j(function(){
        // Set up filters
        $j(".filter input").change(function(){
            processFabric();
            processPallette();
            processPattern();
            $j('.grid').masonry({itemSelector: '.grid-item', columnWidth: '.grid-sizer', percentPosition: true });
        });
        
        $j(".clearall").click( function(){            
            $j(".filter input").each(function(){
                checked = $j(this).is(':checked');
                if (checked) {
                    $j(this).click();
                } 
            });               
        });
        
        //accordian for filters
        enquire.register('(max-width: ' + bp.xsmall + 'px)', {
            match: function () {
                $j(".filter > ul").hide();
            },
            unmatch: function () {
                $j(".filter > ul").show();
            }
        });
        
        $j(".filter > h3").click(function() {                        
            $j(this).next().toggle();
            $j(this).toggleClass("open");
            return false;
        });
        

        //$j("#select_label_colorsofa").html("Click to select...");
        $j("#select_label_colorsofa").click(function(){

            $j('html, body').animate({
                scrollTop: $j(".fabric-swatch").offset().top
            }, 500);
        });
        
        
        $j(".swatch-label").click(function(){
            $j('html, body').animate({
                scrollTop: $j(".product-shop").offset().top
            }, 500);
        });
        
        // info panels
        $j(".info-icon").hover(function(){
            $j(this).find(".pin-arrow").show();
            $j(this).find(".info-block").show();
            
        },function(){
            $j(this).find(".pin-arrow").hide();
            $j(this).find(".info-block").hide();            
        });                
    
        $j(".configurable-swatch-list li").hover(
                function(){
                    
                    popup = $j(this).find(".swatch-expand");
                    popup.show();
                    popup.css("margin-left", 0); // Reset margin in case it has moved
                    var rightEdge = popup.width() + popup.offset().left; // Check for rightEdge position of element
                    var screenWidth = $j(window).width()-15;

                    if (rightEdge > screenWidth) {
                         offset = screenWidth - rightEdge;     // calculate negative offset            
                         popup.css("margin-left", (offset - 30 )+"px");  // increase offset by 30px as it seems to count scrollbar in screen width
                     }
                    $j(this).find(".pin-arrow").show();
                },
                function(){
                    $j(this).find(".swatch-expand").hide();
                    $j(this).find(".pin-arrow").hide();
                }
        );
        
        $j(".swatch-expand button").click(function(){
            $j(this).parent().parent().parent().find(".swatch-label").click();
        });
        

        
        
        /*var popup = $j(this).find(".product-details");
           popup.css("margin-left", 0); // Reset margin in case it has moved
           var rightEdge = popup.width() + popup.offset().left; // Check for rightEdge position of element
           var screenWidth = $j(window).width();
           
           if (rightEdge > screenWidth) {
                offset = screenWidth - rightEdge;     // calculate negative offset            
                popup.css("margin-left", (offset - 30 )+"px");  // increase offset by 30px as it seems to count scrollbar in screen width
            }*/
    });
    
    $j(window).load(function(){
        $j('.grid').masonry({itemSelector: '.grid-item', columnWidth: '.grid-sizer', percentPosition: true });
    });
   // $j(function(){
     //setInterval("$j('.grid').masonry({itemSelector: '.grid-item', columnWidth: '.grid-sizer', percentPosition: true });",1000);
 
    //});
    function processFabric(){
        hascheckfabric = false;
      
        $j(".filter input.fabric").each(function(){
           name = $j(this).attr("name");
           
           checked = $j(this).is(':checked');
           
           if (checked) {
               $j("#"+name).hide();
               if (!checkforempty("#"+name)){
                   $j("#"+name).show();
                }
               hascheckfabric = true;
           }
           else {
               $j("#"+name).hide();
           }               
        });
        
        if (!hascheckfabric) {
            $j(".grid-item").each(function(){
                $j(this).hide();
                if (!checkforempty(this)){
                    $j(this).show();
                }
            });
        }        
    }
    
    function processPallette(){
        hascheck = false;
        
        $j(".filter input.pallette").each(function(){
           name = $j(this).attr("name");
           
           checked = $j(this).is(':checked');
           
           if (checked) {
               $j("."+name).addClass("show-pallette");
               hascheck = true;
           }
           else {
               $j("."+name).removeClass("show-pallette");
           }               
        });
        
        if (!hascheck) {
            $j(".input-box ul li").each(function(){
                $j(this).addClass("show-pallette");
            });
        }
        
        processFabric();
    }
    
    function processPattern(){
        hascheck = false;
        
        $j(".filter input.pattern").each(function(){
           name = $j(this).attr("name");
           
           checked = $j(this).is(':checked');
           
           if (checked) {
               $j("."+name).addClass("show-pattern");
               hascheck = true;
           }
           else {
               $j("."+name).removeClass("show-pattern");
           }               
        });
        
        if (!hascheck) {
            $j(".input-box ul li").each(function(){
                $j(this).addClass("show-pattern");
            });        
        }        
        
        processFabric();
    }
    
    function checkforempty( fabricgroup ) {
            var isempty=true;
            $j(fabricgroup).find("li").each(function(){
                if($j(this).css("display") === "block"){
                    isempty = false;
                };
            });
            
            if (isempty) {
                return true
            }
            else {
               return false
           }        
    }        
    
</script>