
        <?php echo $this->getChildHtml('footer_before') ?>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('global_cookie_notice') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>



<?php
	/* ***************CONVERSATION Code***START::CODE*************************/
	if($GLOBALS['STORE_LIVE_URL']==true){
?>

<?php
	 if(strpos($_SERVER['REQUEST_URI'], "/spsServerPayment/payment/") !== true && ($_SERVER['REQUEST_URI'] !== "/checkout/onepage/success/" || $_SERVER['REQUEST_URI'] != "/checkout/onepage/success/?___SID=S")){	?>
<?php }?>
	
<?php if(curPageURL()=="https://www.willowandhall.co.uk/order-sent")
	  {
?>

	<script type="text/javascript"> if (!window.mstag) mstag = {loadTag : function(){},time : (new Date()).getTime()};</script> <script id="mstag_tops" type="text/javascript" src="//flex.msn.com/mstag/site/ea9e4a68-0f0c-450f-9cf8-1c8da7fa4e51/mstag.js"></script> <script type="text/javascript"> mstag.loadTag("analytics", {dedup:"1",domainId:"2395436",type:"1",actionid:"182059"})</script> <noscript> <iframe src="//flex.msn.com/mstag/tag/ea9e4a68-0f0c-450f-9cf8-1c8da7fa4e51/analytics.html?dedup=1&domainId=2395436&type=1&actionid=182059" frameborder="0" scrolling="no" width="1" height="1" style="visibility:hidden;display:none"> </iframe> </noscript>

<?php }
	  else if(curPageURL()=="https://www.willowandhall.co.uk/checkout/onepage/"){ ?>

     <script type="text/javascript"> if (!window.mstag) mstag = {loadTag : function(){},time : (new Date()).getTime()};</script> <script id="mstag_tops" type="text/javascript" src="//flex.msn.com/mstag/site/ea9e4a68-0f0c-450f-9cf8-1c8da7fa4e51/mstag.js"></script> <script type="text/javascript"> mstag.loadTag("analytics", {dedup:"1",domainId:"2395436",type:"1",actionid:"182060"})</script> <noscript> <iframe src="//flex.msn.com/mstag/tag/ea9e4a68-0f0c-450f-9cf8-1c8da7fa4e51/analytics.html?dedup=1&domainId=2395436&type=1&actionid=182060" frameborder="0" scrolling="no" width="1" height="1" style="visibility:hidden;display:none"> </iframe> </noscript>

<?php } ?>


    <?php
    }
    /* **************CONVERSATION Code***END::CODE************************/
    ?>



<?php
	/* ****************ADROLL TAP Code*******START::CODE**********************/
    if($GLOBALS['STORE_LIVE_URL']==true){
    ?>

<!--ADROLL TAP CODE START-->
<script type="text/javascript">
		
		adroll_adv_id = "EYMQDFFPR5EETCZOMUBRC6";
		adroll_pix_id = "WQ63BVKO25DPLHE5FBHPDG";
		(function () {
			var oldonload = window.onload;
			window.onload = function(){
			__adroll_loaded=true;
			var scr = document.createElement("script");
			var host = (("https:" == document.location.protocol) ? "https://s.adroll.com" : "http://a.adroll.com");
			scr.setAttribute('async', 'true');
			scr.type = "text/javascript";
			scr.src = host + "/j/roundtrip.js";
			((document.getElementsByTagName('head') || [null])[0] ||
			document.getElementsByTagName('script')[0].parentNode).appendChild(scr);
			if(oldonload){oldonload()}};
		}());
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?id=760290647367172&amp;ev=NoScript" /></noscript>
<!--ADROLL TAP CODE END-->

    <?php
    }
    /* ***************ADROLL TAP Code*********END::CODE**************/
    ?>

