<!DOCTYPE html>
<html lang="en">

	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Default with custom name and upload example - Fileuploader</title>

		<!-- Google Fonts -->
		<link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
		
		<!-- styles -->
<?php $skin_url =  Mage::getBaseUrl();?>
<!--
		<link href="<?php echo $skin_url?>canvas_uploader/src/jquery.fileuploader.css" media="all" rel="stylesheet">
-->
		
		<!-- js -->
		<script src="https://code.jquery.com/jquery-3.1.1.min.js" crossorigin="anonymous"></script>
		<script src="<?php echo $skin_url?>canvas_uploader/src/jquery.fileuploader.min.js" type="text/javascript"></script>
		<script src="<?php echo $skin_url?>canvas_uploader/js/custom.js" type="text/javascript"></script>

		<style>

			body {
				font-family: 'Roboto', sans-serif;
				font-size: 14px;
                line-height: normal;
				color: #47525d;
				background-color: #fff;

				margin: 0;
				padding: 20px;
				
				width: 560px;
			}
			
			label {
				display: block;
				font-weight: bold;
			}
			
			input[type="text"],
			input[type="email"] {
				padding: 6px;
				margin-bottom: 10px;
			}


			.fileuploader-item .progress-bar2 .fileuploader-progressbar{
				height: 6px !important;
				top: inherit !important;
				bottom: 0 !important;
			}
			.fileuploader-item .progress-bar2 .fileuploader-progressbar .bar{
				background: #08b3df !important;
			}
		</style>
	</head>

	<body>
<!--
        <label>New file name:</label>
        <input type="text" id="custom_file_name">
-->

        <input type="file" name="files">
    </body>
</html>
