<?php

/*
* Author: Shourya-Uniterrene
* Description: Added the code for the header part of the editor
*/
?>
<?php $skin_url =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>
<head>
    <!-- Meta Tags -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="generator" content="traque" />
    <title>Canvas Signages - Canvas Print</title>
    <meta property="og:title" content="canvassignages" />
    <meta property="og:site_name" content="canvassignages" />
    <meta property="og:url" content="www.canvassignages.com" />
    <meta property="og:type" content="website">
    <meta property="og:image" content="www.canvassignages.com/images/social.jpg" />
    <meta property="og:description" content="Short Description of Site" />
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:100,300,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
    <!-- Stylesheets -->
    
    <link rel="shortcut icon" href="https://www.canvassignages.com/skin/frontend/base/default/favicon.ico" />
    <link rel="stylesheet" type="text/css" href="<?php echo $skin_url?>frontend/revivalpixel/canvas/css/canvas_live_editor/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $skin_url?>frontend/revivalpixel/canvas/css/canvas_live_editor/style.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $skin_url?>frontend/revivalpixel/canvas/css/canvas_live_editor/editor.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $skin_url?>frontend/revivalpixel/canvas/css/canvas_live_editor/before-after.css">
    <!--
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/css/font-awesome.min.css">
--><link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- css added for development -->
    <link rel="stylesheet" type="text/css" href="<?php echo $skin_url?>frontend/revivalpixel/canvas/css/canvas_live_editor/color-picker.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $skin_url?>frontend/revivalpixel/canvas/css/canvas_live_editor/custom.css">

    <link href="<?php echo $skin_url?>frontend/revivalpixel/canvas/css/canvas_live_editor/bootstrap-colorpicker.min.css" rel="stylesheet">

    <!--[if lt IE 9]>
        <script src="js/html5.js"></script>
    <![endif]-->
</head>
