<?php $skin_url =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN).'frontend/jwelzhq/default/images';?>
<div id="content_container" class="pure-margin-zoom">
	<figure class="carousel lazyloaded" data-bgset="<?php echo $skin_url; ?>/desktop.jpg 1x, <?php echo $skin_url; ?>/desktop_2x.jpg 2x [--desktop]" style="background-image: url(<?php echo $skin_url; ?>/desktop.jpg);">
		<a class="carousel__link" href="#">
			<img alt="Promise rings" class="pure-img pure-hidden-lg-up lazyloaded" data-parent-fit="width" data-srcset="<?php echo $skin_url; ?>/mobile.jpg 767w, <?php echo $skin_url; ?>/tablet.jpg 1005w" srcset="<?php echo $skin_url; ?>/mobile.jpg 767w, <?php echo $skin_url; ?>/tablet.jpg 1005w">
		</a>
		<picture style="display: none;">
			<source data-srcset="<?php echo $skin_url; ?>/desktop.jpg 1x, <?php echo $skin_url; ?>/desktop_2x.jpg 2x" media="(min-width: 768px)" sizes="1349px" srcset="<?php echo $skin_url; ?>/desktop.jpg 1x, <?php echo $skin_url; ?>/desktop_2x.jpg 2x">
			<img alt="" class="lazyautosizes lazyloaded" data-sizes="auto" data-parent-fit="cover" sizes="1349px">
		</picture>
	</figure>
	
	<div class="container">
		<h2 class="homepage__header">New Arrivals</h2>
		
		
		
		<div class="best-seller__slider">
			<img alt="Slide left" class="js-slide-left slider__arrow slider__arrow--left" src="<?php echo $skin_url; ?>/left-arrpw.png">
			<img alt="Slide right" class="js-slide-right slider__arrow slider__arrow--right" src="<?php echo $skin_url; ?>/right-arrow.png">
			<div class="js-slider slider">
				<?php 
					$collection = Mage::getModel('catalog/product')->getCollection();
					$collection->addAttributeToSelect('name');
					$collection->addAttributeToSelect('price');
					$collection->addAttributeToSelect('image');
					$collection->addAttributeToSelect('url_path');
					$collection->addAttributeToSelect('short_description');
					$collection->setOrder('entity_id', 'DESC');
					$collection->setPageSize(8);
					$collection->addAttributeToFilter('newarrival', array('eq' => 1));
					
					foreach ($collection as $product) { 
						if($product['image'] !='') {
							$img = Mage::getBaseUrl('media') . "catalog/product" . $product['image'];
							} else {
							$img = $this->getSkinUrl('images/no_image.jpg', array('_secure'=>true));
						}
						//echo $product['name'].$product['image'];
						?>
					<figure class="slider__item">
						<a href="<?php echo $product['url_path'];?>"><img class="pure-img" alt="<?php echo $product['name'];?>" title="<?php echo $product['name'];?>" src="<?php echo $img; ?>" width="256" height="256"></a>
					</figure>
					<?php 
						
					}
				?>
				
				
			</div>
		</div>
		<h2 class="homepage__header">Personalized Jewelry.<br>Handcrafted, just for you.</h2>
		
		<div class="pure-g row row--mothers">
			<div class="col pure-u-1-1 pure-u-md-2-3">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mothers_ring')->toHtml() ?>
			</div>
			<div class="col pure-u-1-1 pure-u-md-1-3">
				
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('promise_ring')->toHtml() ?>
			</div>
		</div>
		<div class="pure-g row row--necklace">
			<div class="col pure-u-1-1">
			
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('name_necklaces')->toHtml() ?>
			</div>
		</div>
		
		
		<div class="row mb-5">
			<div class="order-perks">
				<ul class="text-center list-unstyled">
					
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('middle_link_block')->toHtml() ?>
				</ul>
			</div>
		</div>
		
		
		
		<div class="pure-g row row--mens">
		
			<div class="col pure-u-1-1 pure-u-md-1-3">
			
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mens_ring')->toHtml() ?>
			</div>
			
			<div class="col pure-u-1-1 pure-u-md-2-3">
			
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('bridal_collection')->toHtml() ?>
				
			</div>
		</div>
		
		<div class="pure-g row row--birthstone">
			<div class="col pure-u-1-1 pure-u-md-1-3">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('birthstone_rings ')->toHtml() ?>
			</div>
			<div class="mb-5 col pure-u-1-1 pure-hidden-md-up">
				<div class="order-perks pure-hidden-md-up">
					<ul class="text-center list-unstyled">
						<li class="order-perks__item">
							<a class="order-perks__link" href="#">Free resizing</a>
						</li>
						<li class="order-perks__item order-perks__item--last">
							<a class="order-perks__link" href="#">Made in USA &amp; Canada</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="col pure-u-1-1 pure-u-md-1-3">
			
				
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('couple_rings')->toHtml() ?>
			</div>
			<div class="col pure-u-1-1 pure-u-md-1-3">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pendants')->toHtml() ?>
			</div>
		</div>
		<div class="pure-g row row--princess">
			<div class="col pure-u-1-1">
			
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('princess_collection')->toHtml() ?>
				
			</div>
		</div>
		<div class="pure-g row row--cage">
			<div class="col pure-u-1-1 pure-u-md-2-3">
			
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('caged_jewelry')->toHtml() ?>	
				
			</div>
			<div class="col pure-u-1-1 pure-u-md-1-3">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('celtic_claddagh_rings')->toHtml() ?>
				
			</div>
		</div>
		
		
		<!--review part-->
		<div class="row mb-5">
			<div class="reviews">
				<img alt="Go to previous review" class="js-reviews-prev' reviews__arrow--left reviews__arrow" src="https://j4-assets-jewlr.netdna-ssl.com/assets/icons/arrow_left-4157769a3e7738bef89d87ff8e8e1365569ae83ff3b5d726c71d4562634a0daf.svg" width="15">
				<img alt="Go to next review" class="js-reviews-next reviews__arrow--right reviews__arrow" src="https://j4-assets-jewlr.netdna-ssl.com/assets/icons/arrow_right-67ab7acfa3e79bd9c4eda45b2a0c05dcff316394859e7dccd6576e921e210393.svg" width="15">
				<h2 class="reviews__title clearfix">We're proud of our reviews</h2>
				<div class="js-reviews-slider reviews__slider slick-initialized slick-slider">
					<div aria-live="polite" class="slick-list draggable" tabindex="0">
						<div class="slick-track" style="opacity: 1; width: 4752px; transform: translate3d(-3168px, 0px, 0px);">
							<p class="reviews__quote slick-slide slick-cloned" data-slick-index="-1" aria-hidden="true" style="width: 792px; display: block;">
								"The experience was simple and went smoothly! What a great way to shop." - James F.
							</p>
							<p class="reviews__quote slick-slide" data-slick-index="0" aria-hidden="true" style="width: 792px; display: block;">
								"I love all the choices and options to customize! It made the experience fun and nice..." - CJ
							</p>
							<p class="reviews__quote slick-slide" data-slick-index="1" aria-hidden="true" style="width: 792px; display: block;">
								"My ring was just as beautiful as the woman I gave it to!" - Kristen T.
							</p>
							<p class="reviews__quote slick-slide" data-slick-index="2" aria-hidden="true" style="width: 792px; display: block;">
								"Great choices at VERY affordable prices. Love it!!" - Kenny M.
							</p>
							<p class="reviews__quote slick-slide slick-active" data-slick-index="3" aria-hidden="false" style="width: 792px; display: block;">
								"The experience was simple and went smoothly! What a great way to shop." - James F.
							</p>
							<p class="reviews__quote slick-slide slick-cloned" data-slick-index="4" aria-hidden="true" style="width: 792px; display: block;">
								"I love all the choices and options to customize! It made the experience fun and nice..." - CJ
							</p>
						</div>
					</div>
				</div>
				<g:ratingbadge merchant_id="6661494">
					<p class="reviews__amount m-rm">
						<em>We have over 20,000 reviews!</em>
					</p>
				</g:ratingbadge>
			</div>
		</div>
		
		
		<div class="pure-g row row--engagement">
			<div class="col pure-u-1-1">
		
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('engagement_rings')->toHtml() ?>
			
			</div>
		</div>
		<div class="pure-g row row--ear">
			<div class="col pure-u-1-1 pure-u-md-1-3">
			
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('earrings')->toHtml() ?>
				
			</div>
			<div class="col pure-u-1-1 pure-u-md-2-3">
			
				
				
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('bracelets')->toHtml() ?>
				
			</div>
		</div>
		
		<!--Extra signup portion-->
		<div class="row mb-5">
			<div class="vip-signup clearfix">
				<p class="vip-signup__mssg pure-hidden-sm-down">
					Become a Jewlr VIP and<br>receive exclusive discounts
				</p>
				<p class="vip-signup__mssg pure-hidden-md-up">
					Let's keep in touch
				</p>
				<form id="js_vip_signup_form" class="vip-signup__form">
					<input id="vip_signup_input" class="vip-signup__input" name="email" maxlength="60" pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$" placeholder="Enter your email here..." data-trigger="focus" value="" data-original-title="Please enter a valid email address" title="Please enter a valid email address" type="email">
					<button class="vip-signup__submit btn" type="submit" data-gender="Male">Man</button>
					<button class="vip-signup__submit btn" type="submit" data-gender="Female">Woman</button>
				</form>
			</div>
		</div>
		
		
		<div class="pure-g row row--new">
			<div class="col pure-u-1-1 pure-u-md-1-3">
			
				
				
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('new_items')->toHtml() ?>
				
			</div>
			<div class="col pure-u-1-1 pure-u-md-2-3">
			
				
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('choose_design_box')->toHtml() ?>
				
			</div>
		</div>
		<div class="pure-g row row--best">
			<div class="col pure-u-1-1 pure-u-md-2-3">
			
			
				
				
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('best_seller')->toHtml() ?>
				
			</div>
			<div class="col pure-u-1-1 pure-u-md-1-3">
			
				
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('graduation_gifts')->toHtml() ?>	
				
			</div>
		</div>
		<div class="pure-g row row--modern">
			<div class="col pure-u-1-1 pure-u-md-1-3">
			
				
				
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('modern_romance_collection')->toHtml() ?>	
				
			</div>
			<div class="col pure-u-1-1 pure-u-md-2-3">
			
				
				
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('photo_necklace')->toHtml() ?>
				
			</div>
		</div>
		<div class="pure-g row row--charms">
			<div class="col pure-u-1-1 pure-u-md-2-3">
			
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('personalized_charms')->toHtml() ?>
			
			</div>
			
			<div class="col pure-u-1-1 pure-u-md-1-3">
			
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mens_tungsten_rings')->toHtml() ?>
				
			</div>
			
			
		</div>
		<div class="pure-g row row--jahnavi">
			<div class="col pure-u-1-1 pure-u-md-1-3">
			
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mala_collection')->toHtml() ?>
				
			</div>
			<div class="col pure-u-1-1 pure-u-md-2-3">
			
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('swarovski-zirconia')->toHtml() ?>
				
				
			</div>
		</div>
	</div>
</div>