<?php 
   $sku = "fancy-halo-flip-ring";
   $opt_title = "Metal";
   $product_data = $this->getLayout()->getBlockSingleton('Canvassignages_Liveeditor_Block_Monblock')->customCanvasPrint($sku,$opt_title);

  foreach ($product_data as $product_data) {
    if($product_data['default'] == "default")
    {
      $title = $product_data['default_title'];
    }
  }

  $style_title = $title." Style";

 ?>

 <?php 
 $sku = "fancy-halo-flip-ring";
 $product_data = $this->getLayout()->getBlockSingleton('Canvassignages_Liveeditor_Block_Monblock')->customCanvasPrint($sku,$style_title);
foreach ($product_data as $product_data) {

  if($product_data['default']=="default")
  {
    $default_img_url = Mage::getBaseurl().'media/'.$product_data['img_url']; 
    $default_style_title = $product_data['default_title'];
    $default_style_price = $product_data['price'];
    $default_style_price = number_format((float)$default_style_price, 2, '.', ''); 
  }
}
?>  


 <?php 
 $sku = "fancy-halo-flip-ring";
 $opt_title = $style_title." ".$default_style_title." Side 1 Stone 2";
 $product_data = $this->getLayout()->getBlockSingleton('Canvassignages_Liveeditor_Block_Monblock')->customCanvasPrint($sku,$opt_title);

 $stone_array = array();
  ?>


<?php

$i=0;

 foreach($product_data as $dimond_data) {

//print_r($dimond_data);

  if($dimond_data['default']=="default")
  {
    $side1_stone2_image = Mage::getBaseurl().'media/'.$dimond_data['img_url']; 
    $side1_stone2_title = $dimond_data['default_title']; 
    $side1_stone2_price = $dimond_data['price']; 
    $side1_stone2_price = number_format((float)$side1_stone2_price, 2, '.', ''); 
  }

  $img_url = Mage::getBaseurl().'media/'.$dimond_data['img_url']; 

  $stone_array[$i]['category'] = $dimond_data['category'];
  $stone_array[$i]['default_title'] = $dimond_data['default_title'];
  $stone_array[$i]['price'] = $dimond_data['price'];
 
  $stone_array[$i]['paneltype'] = $dimond_data['panel_type'];
  $stone_array[$i]['panelsize'] = $dimond_data['panelsize'];
  $stone_array[$i]['img_url'] = $img_url;
  $stone_array[$i]['sku'] = $dimond_data['sku'];
  $stone_array[$i]['description'] = $dimond_data['description'];
  $stone_array[$i]['stone_order'] = $dimond_data['sort_order'];
 
$i++;

  }

// /print_r($stone_array);

  ?>
 <!-- Stone 2 Pane -->
    <div class="panel panel-default stones_pane s2_pane filtered" data-filters="">
        <!-- Stone 2 Pane Header -->
        <div class="panel-heading clearfix" data-toggle="collapse" data-parent="" href=".gem2Collapse">
            <div class="mw-thumb"> <img width="40" height="40" class="gem2_thumb summary_thumb lazyloaded" src="<?php echo $side1_stone2_image;?>"> </div>
            <div class="mw-desc">
                <h4>Side 1 Stone 2</h4>
                <span class="gem2_description"><?php echo   $side1_stone2_title;?> - January</span> </div>
            <div class="mw-chevron"> <span class="fa fa-angle-right"></span> </div>
            <div class="mw-price"> <span class="gem2_price">$<?php echo $side1_stone2_price;?></span> </div>
        </div>
        <!-- End Stone 2 Pane Header -->
        <!-- Stone 2 Pane Body -->
        <div class="panel-collapse collapse gem2Collapse">
            <div class="panel-body">
                <div class="wizard-pane s2_pane item" data-maparea="gem2" data-summary-field="gem2" data-pref="s2" data-hashid="s2" data-label="Stone 2">
                    <!-- <div class="pane-title">

Choose your stone

</div> -->
                    <div class="pane-content">
                        <div class="option-description option-description-org2">
                            <h3 class="option-item-description1">Garnet (Simulated) - $0</h3>
                            <span class="option-item-stone-size">Stone Size: 4mm x 2mm Baguette Cut Stone</span>
                            <br>
                            <div class="option-item-description1">Birthmonth: January
                                <br><span class="stone_attributes">Attributes: Leadership, Truth, Creativity</span></div>
                        </div>

                        <div class="option-description21 option-description" style="display: none;">
                                                            
                                                        </div>
                        <h4>Genuine Stones&nbsp;&nbsp;<i data-container="body" data-placement="right" title="Genuine Stones include birthstones (representing each month) and gemstones that are featured for their beauty and color. Genuine stones are rarer and more valuable than simulated stones." class="fa fa-question-circle tooltip-w"></i> </h4>
                        <div class="wizard-option-category stone-option-category">
                            <ul class="thumbnails stone_thumbnails list-unstyled list-inline row">

                              <?php foreach($stone_array as $stone_array_data) {
                                                          ?>
                                                            <?php if($stone_array_data['category'] == "Genuine Stones") {
                                                              //print_r($stone_array_data);
                                                              ?>
                                
                                <li class="wizard-option stone-option metal_type_stone1_side2 <?php if($stone_array_data['default']=="default") echo "selected-item";?>" data-sku="<?php echo $stone_array_data['sku']; ?>" data-name="<?php echo $stone_array_data['default_title'];?>"> 

                                                                <img width="40" height="40" alt="" title="" class="lazyautosizes lazyloaded" data-srcset="
                                                                <?php echo $stone_array_data['img_url'];?>" data-sizes="auto" src="<?php echo $stone_array_data['img_url'];?>" sizes="40px" srcset="
                                                                <?php echo $stone_array_data['img_url'];?>" data-sku="<?php echo $stone_array_data['sku'];?>" data-default-name ="<?php echo $stone_array_data['default_title']; ?>" data-default-sku="fancy-halo-flip-ring">
                                                                    <p class="stone-option-info"> <?php echo $stone_array['default_title'];?>
                                                                        <br>
                                                                        <br>
                                                                        <span class="stone_price">$<?php echo $stone_array['price'];?></span> </p>

                                                                 <div class="upper_content2_stone1" style="display: none;">       
                                                                    <h3 class="option-item-description1"><?php echo $stone_array_data['default_title'];?> - $<?php echo $stone_array_data['price'];?></h3>
                                                                    <span class="option-item-stone-size">Stone Size: <?php echo $stone_array_data['panelsize']?></span>
                                                                    <br>
                                                                    <div class="option-item-description">
                                                                    <?php echo $stone_array_data['description']?>
                                                                    <br><span class="stone_attributes">
                                                                    <?php echo $stone_array_data['paneltype'];?></span></div>  
                                                                </div>  

                                                                <div class="top_content" style="display: none">
                                                                  <div class="mw-desc">
                                                                    <h4>Stone 1</h4>
                                                                    <span class="gem1_description"><?php echo $stone_array_data['default_title'];?> - <?php echo $stone_array_data['description']?></span> </div>
                                                                <div class="mw-chevron"> <span class="fa fa-angle-right"></span> </div>
                                                                <div class="mw-price"> <span class="gem1_price">$<?php echo $stone_array_data['price'];?></span> </div>

                                                                </div>



                                                                </li>

                                <?php } ?>


                                                        <?php } ?>
                            </ul>
                        </div>
                        <h4>Simulated Stones&nbsp;&nbsp;<i data-container="body" data-placement="right" title="Simulated (or synthetic) stones are laboratory-created and emulate the characteristics and look of genuine stones. All of our simulated stones are sourced directly from SWAROVSKI GEMS." class="fa fa-question-circle tooltip-w"></i> </h4>
                        <div class="wizard-option-category stone-option-category">
                            <ul class="thumbnails stone_thumbnails list-unstyled list-inline row">
                               
                                
                                <?php foreach($stone_array as $stone_array_data) {
                                                          ?>
                                                            <?php if($stone_array_data['category'] == "Simulated Stones") {?>

                                                       
                                                                
                                                                <li class="wizard-option stone-option metal_type_stone2_side2" data-name="<?php echo $stone_array_data['default_title'];?>"> 

                                                                <img width="40" height="40" alt="" title="" class="lazyautosizes lazyloaded" data-srcset="
                                                                <?php echo $stone_array_data['img_url'];?>" data-sizes="auto" src="<?php echo $stone_array_data['img_url'];?>" sizes="40px" srcset="
                                                                <?php echo $stone_array_data['img_url'];?>" data-sku="<?php echo $stone_array_data['sku'];?>" data-default-name ="<?php echo $stone_array_data['default_title']; ?>" data-default-sku="fancy-halo-flip-ring">
                                                                    <p class="stone-option-info"> <?php echo $stone_array['default_title'];?>
                                                                        <br>
                                                                        <br>
                                                                        <span class="stone_price">$<?php echo $stone_array['price'];?></span> </p>

                                                                 <div class="upper_content2_stone2" style="display: none;">       
                                                                    <h3 class="option-item-description1"><?php echo $stone_array_data['default_title'];?> - $<?php echo $stone_array_data['price'];?></h3>
                                                                    <span class="option-item-stone-size">Stone Size: <?php echo $stone_array_data['panelsize']?></span>
                                                                    <br>
                                                                    <div class="option-item-description">
                                                                    <?php echo $stone_array_data['description']?>
                                                                    <br><span class="stone_attributes">
                                                                    <?php echo $stone_array_data['paneltype'];?></span></div>  
                                                                </div>  

                                                                </li>

                                                            <?php } ?>


                                                        <?php } ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Stone 2 Pane Body -->
    </div>
    <!-- End Stone 2 Pane -->