<!--NEW ARRIVALS Section-->
<section class="new_arrival">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h2 class="homepage__header">New Arrivals</h2>
				<div class="new-arrivals-row">
					<div id="scrollslider" class="scrollSlider">
						<div class="viewport" style="height: auto;">
							<div class="overview">
								<img src="http://onlinedevserver.biz/html/jwelzhq/images/download%20(2).jpg">
								<img src="http://onlinedevserver.biz/html/jwelzhq/images/download%20(2).jpg">
								<img src="http://onlinedevserver.biz/html/jwelzhq/images/download%20(2).jpg">
								<img src="http://onlinedevserver.biz/html/jwelzhq/images/download%20(2).jpg">
								<img src="http://onlinedevserver.biz/html/jwelzhq/images/download%20(2).jpg"> 
							</div>
						</div>
						<div class="scrollbar">
							<div class="track"></div>
						</div>
					</div>
					<a href="#" data-sslider-control='left'>left</a><br>
					<a href="#" data-sslider-control='right'>right</a><br>
				</div>
			</div>
		</div>
	</div>
</section>
<!--End of NEW ARRIVALS Section--> 
<!--Section Just For you-->
<section class="just_for_you">
	<div class="container">
		<div class="row">
			<h2 class="homepage__header">Personalized Jewelry.<br>
			Handcrafted, just for you. </h2>
			<div class="col-md-8 nopadding-right"> 
				
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mothers_ring')->toHtml() ?>
			</div>
			<div class="col-md-4 nopadding-left"> 
				<!--<div class="col-image-box"><a href="#"><img src="http://onlinedevserver.biz/html/jwelzhq/images/1x/promise1x.jpg" class="img-responsive" /> </a> </div>
					<div class="image_text t--promise">
					<h2 class="homepage__title"><a href="#"> Promise Rings </a></h2>
				<a class="l--promise homepage__link" href="#">For Her <i class="fa fa-angle-right"></i></a> <a class="l--promise homepage__link" href="#">For Him <i class="fa fa-angle-right"></i></a> </div>-->
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('promise_ring')->toHtml() ?>
			</div>
		</div>
	</div>
</section>
<!--End Section just for you --> 
<!--Section name necklaces-->
<section class="name_necklaces">
	<div class="container">
		<div class="row">
			<div class="col-md-12"> 
				<!--<div class="col-image-box"><a href="#"><img class="img-responsive" src="http://onlinedevserver.biz/html/jwelzhq/images/1x/namenecklaces1x.jpg"/></a> </div>
					<div class="image_text t--name ">
					<h2 class="homepage__title"><a href="#"> Name Necklaces </a> </h2>
					<a class="l--name homepage__link" href="#">Name <i class="fa fa-angle-right"></i></a> <a class="l--name homepage__link" href="#">Bar <i class="fa fa-angle-right"></i></a> <a class="l--name homepage__link" href="#">Monogram <i class="fa fa-angle-right"></i></a> <a class="l--name homepage__link" href="#">Initial <i class="fa fa-angle-right"></i></a> 
				</div>-->
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('name_necklaces')->toHtml() ?>
			</div>
		</div>
	</section>
	<!--end of name necklaces--> 
	<!--Free Shipping Black Box-->
	<section class="shipping_black_box">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="order-perks">
						<!--<ul class="text-center list-unstyled">
							<li class="order-perks__item"> <a class="order-perks__link" href="#">Free Shipping</a> </li>
							<li class="order-perks__item"> <a class="order-perks__link" href="#">99-Day Returns</a> </li>
							<li class="order-perks__item order-perks__item--last"> <a class="order-perks__link" href="#">Free Gift</a> </li>
							<li class="order-perks__item pure-hidden-sm-down"> <a class="order-perks__link" href="#">Free resizing</a> </li>
							<li class="order-perks__item pure-hidden-sm-down"> <a class="order-perks__link" href="#">One-Year Warranty</a> </li>
							<li class="order-perks__item pure-hidden-sm-down"> <a class="order-perks__link" href="#">Made in USA &amp; Canada</a> </li>
						</ul>-->
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('middle_link_block')->toHtml() ?>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!--Free Shipping Black Box end--> 
	<!--Home Images Section -->
	<section class="home_images">
		<div class="container">
			<div class="row">
				<div class="col-md-4 nopadding-right"> 
					<!--<div class="col-image-box"><a href="#"><img class="img-responsive" src="http://onlinedevserver.biz/html/jwelzhq/images/1x/mens1x.jpg"/> </a> </div>
						<div class="image_text t--mens">
						<h2 class="homepage__title"><a href="#"> Men's Rings <i class="fa fa-angle-right"></i> </a> </h2>
					</div>-->
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mens_ring')->toHtml() ?>
				</div>
				<div class="col-md-8 nopadding-left"> 
					<!--<div class="col-image-box"> <a href="#"><img class="img-responsive" src="http://onlinedevserver.biz/html/jwelzhq/images/1x/bridal1x.jpg"/> </a> </div>
						<div class="image_text t--bridal">
						<h2 class="homepage__title"><a href="#"> Bridal Collection </a> </h2>
					<a class="l--bridal homepage__link" href="/engagement-rings">Engagement <i class="fa fa-angle-right"></i></a> <a class="l--bridal homepage__link" href="/bands-for-her">Bands For Her <i class="fa fa-angle-right"></i></a> <a class="l--bridal homepage__link" href="/bands-for-him">Bands For Him <i class="fa fa-angle-right"></i></a> <a class="l--bridal homepage__link" href="/bridesmaids-gifts">Bridesmaids Gifts <i class="fa fa-angle-right"></i></a> </div>-->
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('bridal_collection')->toHtml() ?>
				</div>
			</div>
		</div>
		<div class="three-col-row">
			<div class="container">
				<div class="row">
					<div class="col-md-4 nopadding-right"> 
						<!--<div class="col-image-box"><a href="#"><img class="img-responsive" src="http://onlinedevserver.biz/html/jwelzhq/images/1x/birthstone1x.jpg"/> </a> </div>
							<div class="image_text t--birthstone">
							<h2 class="homepage__title"><a href="#">Pendants <i class="fa fa-angle-right"></i> </a></h2>
						</div>-->
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pendants')->toHtml() ?>
					</div>
					<div class="col-md-4 nopadding-right nopadding-center"> 
						<!--<div class="col-image-box"> <a href="#"><img class="img-responsive" src="http://onlinedevserver.biz/html/jwelzhq/images/1x/couples.jpg"/> </a> </div>
							<div class="image_text t--birthstone">
							<h2 class="homepage__title"><a href="#">Couples Rings <i class="fa fa-angle-right"></i></a></h2>
						</div>-->
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('couple_rings')->toHtml() ?>
					</div>
					<div class="col-md-4 nopadding-left"> 
						<!--<div class="col-image-box"> <a href="#"><img class="img-responsive" src="http://onlinedevserver.biz/html/jwelzhq/images/1x/pendants1x.jpg"/> </a> </div>
							<div class="image_text t--birthstone">
							<h2 class="homepage__title"><a href="#">Pendants <i class="fa fa-angle-right"></i></a></h2>
						</div>-->
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('birthstone_rings ')->toHtml() ?>
					</div>
				</div>
			</div>
		</div>
		<div class="one-col-row">
			<div class="container">
				<div class="row">
					<div class="col-md-12"> 
						<!--<div class="col-image-box"> <a href="#"> <img src="http://onlinedevserver.biz/html/jwelzhq/images/1x/princess1x.jpg" class="img-responsive" /> </div>
							<div class="image_text t--princess">
							<h2 class="homepage__title">
							<a href="#">Princess
							Collection <i class="fa fa-angle-right"></i></a></h2>
							</div>
						</a>--> 
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('princess_collection')->toHtml() ?>
					</div>
				</div>
			</div>
		</div> 
		<div class="two-col-row">
			<div class="container">
				<div class="row">
					<div class="col-md-8 nopadding-right"> 
						<!--<div class="col-image-box"> <a href="#"><img class="img-responsive" src="{{skin url='images/cage-1.jpg'}}"/> </a> </div>
							<div class="image_text t--bridal">
							<h2 class="homepage__title"><a href="#"> Cage jewllery </a> </h2>
						<a class="l--bridal homepage__link" href="/engagement-rings">Engagement <i class="fa fa-angle-right"></i></a> <a class="l--bridal homepage__link" href="/bands-for-her">Bands For Her <i class="fa fa-angle-right"></i></a> <a class="l--bridal homepage__link" href="/bands-for-him">Bands For Him <i class="fa fa-angle-right"></i></a> <a class="l--bridal homepage__link" href="/bridesmaids-gifts">Bridesmaids Gifts <i class="fa fa-angle-right"></i></a> </div>-->
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('caged_jewelry')->toHtml() ?>	
					</div>
					<div class="col-md-4 nopadding-left"> 
						<!--<div class="col-image-box"><a href="#"><img class="img-responsive" src="<?php echo $this->getSkinUrl( 'images/celtic.jpg' );?>"/> </a> </div>
							<div class="image_text t--mens">
							<h2 class="homepage__title"><a href="#"> Men's Rings <i class="fa fa-angle-right"></i> </a> </h2>
						</div>-->
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('celtic_claddagh_rings')->toHtml() ?>
					</div>
				</div>
			</div>
		</div>
		<div class="one-col-row">
			<div class="container">
				<div class="row">
					<div class="col-md-12"> 
						<div class="col-image-box"> <img src="http://onlinedevserver.biz/html/jwelzhq/images/1x/princess1x.jpg" class="img-responsive" /> </div>
						<div class="image_text t--princess">
							<h2 class="homepage__title">
							Slider Section</h2>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="one-col-row">
			<div class="container">
				<div class="row">
					<div class="col-md-12"> 
						<!--<div class="col-image-box"> <a href="#"> <img src="<?php echo $this->getSkinUrl( 'images/engagement_2x.jpg' );?>" class="img-responsive" /> </div>
							<div class="image_text t--princess">
							<h2 class="homepage__title">
							<a href="#">Engagement <i class="fa fa-angle-right"></i></a></h2>
							</div>
						</a> -->
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('engagement_rings')->toHtml() ?>
					</div>
				</div>
			</div>
		</div> 
		<div class="container">
			<div class="row">
				<div class="col-md-4 nopadding-right"> 
					<!--<div class="col-image-box"><a href="#"><img class="img-responsive" src="<?php echo $this->getSkinUrl( 'images/earrings.jpg' );?>"/> </a> </div>
						<div class="image_text t--mens">
						<h2 class="homepage__title"><a href="#"> Earrings <i class="fa fa-angle-right"></i> </a> </h2>
					</div>-->
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('earrings')->toHtml() ?>
				</div>
				<div class="col-md-8 nopadding-left"> 
					<!--<div class="col-image-box"> <a href="#"><img class="img-responsive" src="<?php echo $this->getSkinUrl( 'images/bracelets.jpg' );?>"/> </a> </div>
						<div class="image_text t--mens">
						<h2 class="homepage__title"><a href="#"> Bracelets <i class="fa fa-angle-right"></i></a> </h2>
					</div>-->
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('bracelets')->toHtml() ?>
				</div>
			</div>
		</div>
		<!--Vip-->
		<section class="shipping_black_box">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="order-perks">
							<form action="" method="post" id="jewlr_vip" name="jewlr_vip">
								<div class="block-content">
									<div class="input-box">
										<label for="newsletter">BECOME A JEWLR VIP AND RECEIVE EXCLUSIVE DISCOUNTS </label>
										<input autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="newsletter" title="Sign up for our newsletter" class="input-text required-entry validate-email" type="email">
										<input type="submit" name="submit" onclick="validateForm(this)" value="man" />
										<input type="submit" name="submit" onclick="validateForm(this)" value="woman" />
									</div>
								</div>
							</form>
							<script type="text/javascript">
								var editVip = new VarienForm('jewlr_vip', true);
								function validateForm(button) {
									if (editVip.validator && editVip.validator.validate()) {
										editVip.submit();
									}
								}
							</script>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!--Vip--> 
		<div class="container">
			<div class="row">
				<div class="col-md-4 nopadding-right"> 
					<!--<div class="col-image-box"><a href="#"><img class="img-responsive" src="<?php echo $this->getSkinUrl( 'images/newitems.jpg' );?>"/> </a> </div>
						<div class="image_text t--mens">
						<h2 class="homepage__title"><a href="#"> New Items <i class="fa fa-angle-right"></i> </a> </h2>
					</div>-->
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('new_items')->toHtml() ?>
				</div>
				<div class="col-md-8 nopadding-left"> 
					<!--<div class="col-image-box"> <a href="#"><img class="img-responsive" src="<?php echo $this->getSkinUrl( 'images/desktop1.gif' );?>"/> </a> </div>-->
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('choose_design_box')->toHtml() ?>
				</div>
			</div>
		</div>
		<div class="two-col-row">
			<div class="container">
				<div class="row">
					<div class="col-md-8 nopadding-right"> 
						<!--<div class="col-image-box"> <a href="#"><img class="img-responsive" src="<?php echo $this->getSkinUrl( 'images/bestsellers.jpg' );?>"/> </a> </div>
							<div class="image_text t--bridal">
							<h2 class="homepage__title"><a href="#"> Best Seller <i class="fa fa-angle-right"></i></a> </h2>
						</div>-->
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('best_seller')->toHtml() ?>
					</div>
					<div class="col-md-4 nopadding-left"> 
						<!--<div class="col-image-box"><a href="#"><img class="img-responsive" src="<?php echo $this->getSkinUrl( 'images/eyeglass.jpg' );?>"/> </a> </div>
							<div class="image_text t--mens">
							<h2 class="homepage__title"><a href="#"> eyeglass holder necklaces <i class="fa fa-angle-right"></i> </a> </h2>
						</div>-->
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('graduation_gifts')->toHtml() ?>	
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="col-md-4 nopadding-right"> 
					<!--<div class="col-image-box"><a href="#"><img class="img-responsive" src="<?php echo $this->getSkinUrl( 'images/modernromance.jpg' );?>"/> </a> </div>
						<div class="image_text t--mens">
						<h2 class="homepage__title"><a href="#"> Modern Romance collection <i class="fa fa-angle-right"></i> </a> </h2>
					</div>-->
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('modern_romance_collection')->toHtml() ?>
				</div>
				<div class="col-md-8 nopadding-left"> 
					<!--<div class="col-image-box"> <a href="#"><img class="img-responsive" src="<?php echo $this->getSkinUrl( 'images/photonecklace.gif' );?>"/> </a> </div>
						<div class="image_text t--mens">
						<h2 class="homepage__title"><a href="#"> Photo Frame Necklaces <i class="fa fa-angle-right"></i> </a> </h2>
					</div>-->
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('photo_necklace')->toHtml() ?>
				</div>
			</div>
		</div>
		<div class="two-col-row">
			<div class="container">
				<div class="row">
					<div class="col-md-8 nopadding-right"> 
						<!--<div class="col-image-box"> <a href="#"><img class="img-responsive" src="<?php echo $this->getSkinUrl( 'images/charms.jpg' );?>"/> </a> </div>
							<div class="image_text t--bridal">
							<h2 class="homepage__title"><a href="#"> Charms <i class="fa fa-angle-right"></i></a> </h2>
						</div>-->
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('personalized_charms')->toHtml() ?>
					</div>
					<div class="col-md-4 nopadding-left"> 
						<!--<div class="col-image-box"><a href="#"><img class="img-responsive" src="<?php echo $this->getSkinUrl( 'images/tungsten.jpg' );?>"/> </a> </div>
							<div class="image_text t--mens">
							<h2 class="homepage__title"><a href="#"> Men's Tungsten  <i class="fa fa-angle-right"></i> </a> </h2>
						</div>-->
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mens_tungsten_rings')->toHtml() ?>
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="col-md-4 nopadding-right"> 
					<!--<div class="col-image-box"><a href="#"><img class="img-responsive" src="<?php echo $this->getSkinUrl( 'images/jahnavi.jpg' );?>"/> </a> </div>
						<div class="image_text t--mens">
						<h2 class="homepage__title"><a href="#"> Learn More <i class="fa fa-angle-right"></i> </a> </h2>
					</div>-->
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mala_collection')->toHtml() ?>
				</div>
				<div class="col-md-8 nopadding-left"> 
					<!--<div class="col-image-box"> <a href="#"><img class="img-responsive" src="<?php echo $this->getSkinUrl( 'images/swarovski.jpg' );?>"/> </a> </div>
						<div class="image_text t--mens">
						<h2 class="homepage__title"><a href="#"> Made With Swarovski Zirconia <i class="fa fa-angle-right"></i> </a> </h2>
					</div>-->
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('swarovski-zirconia')->toHtml() ?>
				</div>
			</div>
		</div>
	</section>										