<!--NEW ARRIVALS Section-->
<section class="new_arrival">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h2 class="homepage__header">New Arrivals</h2>
				<div class="new-arrivals-row">
					<div id="scrollslider" class="scrollSlider">
						<div class="viewport" style="height: auto;">
							<div class="overview">
								<img src="http://onlinedevserver.biz/html/jwelzhq/images/download%20(2).jpg">
								<img src="http://onlinedevserver.biz/html/jwelzhq/images/download%20(2).jpg">
								<img src="http://onlinedevserver.biz/html/jwelzhq/images/download%20(2).jpg">
								<img src="http://onlinedevserver.biz/html/jwelzhq/images/download%20(2).jpg">
								<img src="http://onlinedevserver.biz/html/jwelzhq/images/download%20(2).jpg"> 
							</div>
						</div>
						<div class="scrollbar">
							<div class="track"></div>
						</div>
					</div>
					<a href="#" data-sslider-control='left'>left</a><br>
					<a href="#" data-sslider-control='right'>right</a><br>
				</div>
			</div>
		</div>
	</div>
</section>
<!--End of NEW ARRIVALS Section--> 
<!--Section Just For you-->
<section class="just_for_you">
	<div class="container">
		<div class="row">
			<h2 class="homepage__header">Personalized Jewelry.<br>
			Handcrafted, just for you. </h2>
			<div class="col-md-8 nopadding-right"> 
				
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mothers_ring')->toHtml() ?>
			</div>
			<div class="col-md-4 nopadding-left"> 
				
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('promise_ring')->toHtml() ?>
			</div>
		</div>
	</div>
</section>
<!--End Section just for you --> 
<!--Section name necklaces-->
<section class="name_necklaces">
	<div class="container">
		<div class="row">
			<div class="col-md-12"> 
				
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('name_necklaces')->toHtml() ?>
			</div>
		</div>
	</section>
	<!--end of name necklaces--> 
	<!--Free Shipping Black Box-->
	<section class="shipping_black_box">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="order-perks">
						
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('middle_link_block')->toHtml() ?>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!--Free Shipping Black Box end--> 
	<!--Home Images Section -->
	<section class="home_images">
		<div class="container">
			<div class="row">
				<div class="col-md-4 nopadding-right"> 
					
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mens_ring')->toHtml() ?>
				</div>
				<div class="col-md-8 nopadding-left"> 
					
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('bridal_collection')->toHtml() ?>
				</div>
			</div>
		</div>
		<div class="three-col-row">
			<div class="container">
				<div class="row">
					<div class="col-md-4 nopadding-right"> 
						
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pendants')->toHtml() ?>
					</div>
					<div class="col-md-4 nopadding-right nopadding-center"> 
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('couple_rings')->toHtml() ?>
					</div>
					<div class="col-md-4 nopadding-left"> 
						
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('birthstone_rings ')->toHtml() ?>
					</div>
				</div>
			</div>
		</div>
		<div class="one-col-row">
			<div class="container">
				<div class="row">
					<div class="col-md-12"> 
						
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('princess_collection')->toHtml() ?>
					</div>
				</div>
			</div>
		</div> 
		<div class="two-col-row">
			<div class="container">
				<div class="row">
					<div class="col-md-8 nopadding-right"> 
						
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('caged_jewelry')->toHtml() ?>	
					</div>
					<div class="col-md-4 nopadding-left"> 
						
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('celtic_claddagh_rings')->toHtml() ?>
					</div>
				</div>
			</div>
		</div>
		<div class="one-col-row">
			<div class="container">
				<div class="row">
					<div class="col-md-12"> 
						<div class="col-image-box"> <img src="http://onlinedevserver.biz/html/jwelzhq/images/1x/princess1x.jpg" class="img-responsive" /> </div>
						<div class="image_text t--princess">
							<h2 class="homepage__title">
							Slider Section</h2>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="one-col-row">
			<div class="container">
				<div class="row">
					<div class="col-md-12"> 
						
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('engagement_rings')->toHtml() ?>
					</div>
				</div>
			</div>
		</div> 
		<div class="container">
			<div class="row">
				<div class="col-md-4 nopadding-right"> 
					
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('earrings')->toHtml() ?>
				</div>
				<div class="col-md-8 nopadding-left"> 
					
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('bracelets')->toHtml() ?>
				</div>
			</div>
		</div>
		<!--Vip-->
		<section class="shipping_black_box">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="order-perks">
							<form action="" method="post" id="jewlr_vip" name="jewlr_vip">
								<div class="block-content">
									<div class="input-box">
										<label for="newsletter">BECOME A JEWLR VIP AND RECEIVE EXCLUSIVE DISCOUNTS </label>
										<input autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="newsletter" title="Sign up for our newsletter" class="input-text required-entry validate-email" type="email">
										<input type="submit" name="submit" onclick="validateForm(this)" value="man" />
										<input type="submit" name="submit" onclick="validateForm(this)" value="woman" />
									</div>
								</div>
							</form>
							<script type="text/javascript">
								var editVip = new VarienForm('jewlr_vip', true);
								function validateForm(button) {
									if (editVip.validator && editVip.validator.validate()) {
										editVip.submit();
									}
								}
							</script>
						</div>
					</div>
				</div>
			</div>
		</section>
		<!--Vip--> 
		<div class="container">
			<div class="row">
				<div class="col-md-4 nopadding-right"> 
					
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('new_items')->toHtml() ?>
				</div>
				<div class="col-md-8 nopadding-left"> 
					
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('choose_design_box')->toHtml() ?>
				</div>
			</div>
		</div>
		<div class="two-col-row">
			<div class="container">
				<div class="row">
					<div class="col-md-8 nopadding-right"> 
						
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('best_seller')->toHtml() ?>
					</div>
					<div class="col-md-4 nopadding-left"> 
						
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('graduation_gifts')->toHtml() ?>	
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="col-md-4 nopadding-right"> 
					
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('modern_romance_collection')->toHtml() ?>
				</div>
				<div class="col-md-8 nopadding-left"> 
					
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('photo_necklace')->toHtml() ?>
				</div>
			</div>
		</div>
		<div class="two-col-row">
			<div class="container">
				<div class="row">
					<div class="col-md-8 nopadding-right"> 
						
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('personalized_charms')->toHtml() ?>
					</div>
					<div class="col-md-4 nopadding-left"> 
						
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mens_tungsten_rings')->toHtml() ?>
					</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="col-md-4 nopadding-right"> 
					
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mala_collection')->toHtml() ?>
				</div>
				<div class="col-md-8 nopadding-left"> 
					
					<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('swarovski-zirconia')->toHtml() ?>
				</div>
			</div>
		</div>
	</section>										