<?php

/*
* Author: Shourya-Uniterrene
* Description: Added the code for the size section for custom-canvas-print products
* Date: 10-8-17
* Version: 1.0
*/
?>
<?php $skin_url =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>
<!--Get the magento product data-->
        
        
        
    <?php 
        $product_sku = 'custom-canvas-print';
        $product = Mage::getModel('catalog/product')->loadByAttribute('sku', $product_sku);
        $product_id = 1;
        $obj = Mage::getModel('catalog/product');
        $product = $obj->load($product_id);
        
        foreach($product->getOptions() as $o)

        {
            
            $options = $o->getData();
            $optionType = $o->getType();
            $option_title = $options['default_title'];
            
            if($option_title == "Canvas Type")
            {
                $values = $o->getValues();

                foreach ($values as $k => $v) 
                {
                    $ipt_title = $v->getData();
                    
                     $canvas_type_option_title = $ipt_title['default_title'];
                    
                    
                }
            }
            
        }   
        
    ?>  
<a href="#" class="link">
                            <img src="<?php echo $skin_url?>frontend/rwd/default/images/canvas_live_editor/images/size.png" alt="Editor Icon">
                            <span>Size</span>
                        </a>
                        <div class="sidebar-content size-prize ">                        
                            <ul class="nav nav-tabs" role="tablist">
                                <li role="presentation" data-canvas-type="rolled_canvas">
                                    <a href="#Thin-Gallery" role="tab" data-toggle="tab" aria-expanded="true">
                                        <img src="<?php echo $skin_url?>frontend/rwd/default/images/canvas_live_editor/images/Rolled-Canvas.jpg" alt="Size">
                                        <img src="<?php echo $skin_url?>frontend/rwd/default/images/canvas_live_editor/images/select-check.png" class="select-image" alt="Select Image">
                                        <span>Rolled <br>Canvas</span>
                                    </a>
                                </li>
                                <li role="presentation" data-canvas-type="thin_gallery">
                                    <a href="#Thin-Gallery " role="tab" data-toggle="tab" aria-expanded="false">
                                        <img src="<?php echo $skin_url?>frontend/rwd/default/images/canvas_live_editor/images/Thin-Gallery.jpg" alt="Size">
                                        <img src="<?php echo $skin_url?>frontend/rwd/default/images/canvas_live_editor/images/select-check.png" class="select-image" alt="Select Image">
                                        <span>Thin Gallery Wrap (0.75")</span>
                                    </a>
                                </li>
                                <li role="presentation" data-canvas-type="thick_gallery">
                                    <a href="#Thin-Gallery " role="tab" data-toggle="tab" aria-expanded="false">
                                        <img src="<?php echo $skin_url?>frontend/rwd/default/images/canvas_live_editor/images/Thick-Gallery.jpg" alt="Size">
                                        <img src="<?php echo $skin_url?>frontend/rwd/default/images/canvas_live_editor/images/select-check.png" class="select-image" alt="Select Image">
                                        <span>Thick Gallery Wrap (1.5")</span>
                                    </a>
                                </li>
                            </ul>
                            <div class="tab-content">
                              
                                <div role="tabpanel" class="tab-pane active" id="Thin-Gallery">
                                    <div class="price-size-table">
                                        <ul class="list-unstyled">
                                            <li class="sub-title">
                                                <span class="size-title">Select size</span>
                                                <span class="discount-title">discounted prize</span>
                                            </li>
                                            <li>
                                                <input id="option7" name="selector1" data-w="8" data-h="8" type="radio">
                                                <label for="option7">8x8"</label>
                                                <div class="check"></div>
                                                <span class="price">
                                                <strike>$37.09</strike> $6.69
                                            </span>
                                            </li>
                                            <li>
                                                <input id="option8" name="selector1" data-w="8" data-h="12" type="radio">
                                                <label for="option8">8x12"</label>
                                                <div class="check"></div>
                                                <span class="price">
                                                <strike>$37.09</strike> $12.61
                                            </span>
                                            </li>
                                            <li>
                                                <input id="option9" name="selector1" data-w="9" data-h="9" type="radio">
                                                <label for="option9">9x9"</label>
                                                <div class="check"></div>
                                                <span class="price">
                                                <strike>$37.09</strike> $10.07
                                            </span>
                                            </li>
                                            <li>
                                                <input id="option10" name="selector1" data-w="16" data-h="12" type="radio">
                                                <label for="option10">16x20"</label>
                                                <div class="check"></div>
                                                <span class="price">
                                                <strike>$37.09</strike> $28.41
                                            </span>
                                            </li>
                                            <li>
                                                <input id="option11" name="selector1" data-w="18" data-h="36" type="radio">
                                                <label for="option11">18x36"</label>
                                                <div class="check"></div>
                                                <span class="price">
                                                <strike>$37.09</strike> $50.97
                                            </span>
                                            </li>
                                            <li class="custom-size">
                                                <input id="option12" name="selector1" data-w="custom" data-h="custom" type="radio">
                                                <label for="option12">Custom Size</label>
                                                <div class="check"></div>
                                                <div class="select-box">
                                                    <select disabled="true" class="disable">
                                                        <option>8</option>
                                                        <option>9</option>
                                                        <option>10</option>
                                                        <option>11</option>
                                                        <option>12</option>
                                                    </select>
                                                    x
                                                    <select disabled="true" class="disable">
                                                        <option>8</option>
                                                        <option>9</option>
                                                        <option>10</option>
                                                        <option>11</option>
                                                        <option>12</option>
                                                    </select>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
