<!DOCTYPE html>
<html>
<head>
<?php echo $this->getChildHtml('head') ?>
<?php echo $this->getChildHtml('header') ?>

<?php echo $this->getChildHtml('content') ?>

<!-- Footer -->
<?php echo $this->getChildHtml('global_messages') ?>

<?php echo $this->getChildHtml('footer_before') ?>
<?php echo $this->getChildHtml('footer') ?>
<?php echo $this->getChildHtml('global_cookie_notice') ?>
<?php echo $this->getChildHtml('before_body_end') ?>
