<?php
/*
* Template For Showing The Metal Content
*/

?>

 <?php 
 $sku = "fancy-halo-flip-ring";
 $opt_title = "Metal";
 $product_data = $this->getLayout()->getBlockSingleton('Canvassignages_Liveeditor_Block_Monblock')->customCanvasPrint($sku,$opt_title);
  ?>
  <div class="panel panel-default sku_pane">
                                        <!-- Metal Pane Header -->
                                        <div class="panel-heading clearfix" data-toggle="collapse" data-parent="" href=".skuCollapse">
                                            <div class="mw-thumb mw-thumb-metal"> 


                                            <img width="40" height="40" class="sku_thumb summary_thumb summary_thumb_metal lazyloaded" src="./JWELZHQ_files/jewlr-4a34acfad1ff8388b748c3eb253a6fbb5b3e4fbe9a34cbeaf169de003c69853b.gif" alt="Jewlr" srcset="https://j4-assets-jewlr.netdna-ssl.com/assets/product/sku/1x/SS-9d06a9f9a8ec033f4cfb8428e39c35ba071842750726f221f2404792cd898767.png 1x, https://j4-assets-jewlr.netdna-ssl.com/assets/product/sku/2x/SS-e51eee7e95e743843f3e9cbea865b6995749c6dcdd422d5d1e0c60542284feb4.png 2x"> </div>
                                            <div class="mw-desc">
                                                <h4>Metal</h4>
                                                <span class="sku_description sku_description_metal">Sterling Silver</span> </div>
                                            <div class="mw-chevron"> <span class="fa fa-angle-right"></span> </div>
                                            <div class="mw-price"> <span class="sku_price">$109</span> </div>
                                        </div>


                       <div class="panel-collapse collapse skuCollapse">
                                            <div class="panel-body">
                                                <div class="wizard-pane sku_pane item" data-maparea="shank" data-summary-field="sku" data-pref="sku" data-hashid="sku" data-label="Metal">
                                                    
                                                    <!-- end div pane-title -->
                                                    <div class="pane-content clearfix">
                                                        <div class="wizard-option-category">
                                                            <ul class="thumbnails list-unstyled list-inline">

                                                            <?php foreach($product_data as $dimond_data) {?>
   		    													<?php $img_url = Mage::getBaseurl().'media/'.$dimond_data['img_url']; ?>                                                           

                                                                <li data-title="14K Rose Gold" data-description="A higher % of pure gold than 10K.&lt;br/&gt;A distinct look with a rosy hue." data-price="329" data-sia="0" data-value="14KR" data-filter="gold" data-category="14K Gold" data-more-info-pane="sku-more-info" class="wizard-option metal-item metal_type <?php if($dimond_data['default']=="default") echo "selected-item";?>"> 

                                                                <img height="40" width="40" alt="14K Rose Gold" title="14K Rose Gold" class="lazyautosizes lazyloaded" data-srcset="<?php echo $img_url;?>" data-sizes="auto" src="<?php echo $img_url;?>" sizes="40px" srcset="<?php echo $img_url;?>" data-sku="<?php echo $dimond_data['sku'];?>" data-default-sku="fancy-halo-flip-ring" data-default-name ="<?php echo $dimond_data['default_title']; ?>">
                                                                    <p><small><?php echo $dimond_data['default_title']; ?></small></p>
                                                                    <p> $<?php echo $dimond_data['price']; ?> </p>
                                                                </li>

                                                                <?php }?>

                                                            </ul>
                                                        </div>
                                                    </div>
                                                    <!-- HOLIDAY GUARANTEE FOR METAL -->
                                                    <div id="metal-guarantee" class="clearfix">
                                                        <div class="guarantee-icon-container pull-left"></div>
                                                        <div class="guarantee-text-container"></div>
                                                    </div>
                                                    <div id="metal-guarantee-details">
                                                        <div class="guarantee-details-container"></div>
                                                    </div>
                                                    <!-- END HOLIDAY GUARANTEE FOR METAL -->
                                                    <!-- end div pane-content -->
                                                </div>
                                            </div>
                                        </div>
                                </div>        

