<?php

/**
* Template is for the style part of the product page
*/

?>

 <?php 
	 $sku = "fancy-halo-flip-ring";
	 $opt_title = "Metal";
	 $product_data = $this->getLayout()->getBlockSingleton('Canvassignages_Liveeditor_Block_Monblock')->customCanvasPrint($sku,$opt_title);

	foreach ($product_data as $product_data) {
		if($product_data['default'] == "default")
		{
			$title = $product_data['default_title'];
		}
	}

	$style_title = $title." Style";

 ?>

  <?php 
 $sku = "fancy-halo-flip-ring";
 $product_data = $this->getLayout()->getBlockSingleton('Canvassignages_Liveeditor_Block_Monblock')->customCanvasPrint($sku,$style_title);
foreach ($product_data as $product_data) {

	if($product_data['default']=="default")
	{
		$default_img_url = Mage::getBaseurl().'media/'.$product_data['img_url']; 
		$default_style_title = $product_data['default_title'];
		$default_style_price = $product_data['price'];
		$default_style_price = number_format((float)$default_style_price, 2, '.', ''); 
	}
}
?>														 	


					 <div class="panel panel-default stylePanel">
										   <div class="panel-heading clearfix" data-toggle="collapse" data-parent="" href=".facesCollapse">
										      <div class="mw-thumb">
										         <img width="40" height="40" class="summary_thumb faces_thumb" src="<?php echo $default_img_url?>" alt="Jewlr" data-pagespeed-url-hash="120461313">
										      </div>
										      <div class="mw-desc">
										         <h4>Style</h4>
										         <span class="faces_description"><?php echo $default_style_title;?></span>
										      </div>
										      <div class="mw-chevron">
										         <span class="fa fa-angle-right"></span>
										      </div>
										      <div class="mw-price">
										         <span class="faces_price">$<?php echo $default_style_price;?></span>
										      </div>
										   </div>
										   <div class="panel-collapse facesCollapse collapse" aria-expanded="false">
										      <div class="panel-body styles_panel">
										         <div class="wizard-pane face_pane faces_pane item" data-summary-field="faces" data-pref="faces" data-hashid="faces" data-label="Side 2">
										            <div class="pane-content clearfix">
										               <div class="option-description">
										                  <h3 class="option-item-description1"><?php echo $default_style_title;?> - $<?php echo $default_style_price;?></h3>
										                  <div class="option-item-description2">A round 4mm gemstone surrounded by a halo of accent stones</div>
										               </div>
										               <div class="wizard-option-category">
										                  <ul class="thumbnails list-unstyled list-inline">

										                  <?php 
														 $sku = "fancy-halo-flip-ring";
														 
														 $product_data = $this->getLayout()->getBlockSingleton('Canvassignages_Liveeditor_Block_Monblock')->customCanvasPrint($sku,$style_title);

														 foreach ($product_data as $product_data) {
														 	$img_url = Mage::getBaseurl().'media/'.$product_data['img_url']; ?>
														
										                     <li data-title="Gemstone Filigree Side" data-price="0" data-value="01" data-filter="14K Gold" data-summary-field="faces" data-description="Gemstone Filigree Side - $0" data-description2="A round 4mm gemstone surrounded by decorative detailing" data-specs="Main Stone: One 4mm Round Stone" class="wizard-option face-option">
										                        <img width="50" height="50" alt="" title="" class="extimage" src="<?php echo $img_url;?>" data-pagespeed-url-hash="708250024" onload="pagespeed.CriticalImages.checkImageForCriticality(this);"> 
										                        <p>
										                           <?php echo $product_data['default_title'];?><br>
										                        </p>
										                     </li>
										                    
										                      <?php }
														 ?>
										                    
										                    
										                     
										                     
										                  </ul>
										               </div>
										            </div>
										         </div>
										      </div>
										   </div>
										</div>