<?php echo $this->getChildHtml('header') ?>
<?php $skin_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>
<link rel="stylesheet" type="text/css" href="<?php echo $skin_url ?>frontend/revivalpixel/canvas/css/canvas_live_editor/before-after.css">
<!-- Main Content -->
<div class="main-content">
    <?php
    if (Mage::registry('current_product')) { //check if product global 'registry' object is available
        $product = Mage::registry('current_product');
        $sku = $product->getSku();
    }
    ?>

    <!-- Main Banner -->
    <?php
    $attribute = $product->getCanvasBanner();
    $attributeName = 'canvas_banner';
    echo $this->helper('catalog/output')->productAttribute($product, $attribute, $attributeName);
    ?>

    <!-- Offer Box -->
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_discount')->toHtml(); ?> 

    <!-- FIxed Navigation -->
    <?php
    $attribute = $product->getFlexNavigation();
    $attributeName = 'flex_navigation';
    echo $this->helper('catalog/output')->productAttribute($product, $attribute, $attributeName);
    ?>


    <!-- How It Works -->
    <?php
    $attribute = $product->getHowItWork();
    $attributeName = 'how_it_work';
    echo $this->helper('catalog/output')->productAttribute($product, $attribute, $attributeName);
    ?>

    <!-- Frame Art -->
    <?php
    $attribute = $product->getFrameArt();
    $attributeName = 'frame_art';
    echo $this->helper('catalog/output')->productAttribute($product, $attribute, $attributeName);
    ?>

    <!-- Photo Effect -->
    <div class="photo-effect padding-70" id="photo-effect">
        <div class="container text-center">
            <div class="row">
                <h3>photo effects</h3>
                <p>Give a contemporary touch to your heart flow <br />moments with custom floating frames.</p>
                <?php $opt_title = "Photo Filters"; ?>
                <?php $product_data = $this->getLayout()->getBlockSingleton('Canvassignages_Liveeditor_Block_Monblock')->customCanvasPrint($sku, $opt_title); ?>
                <div class="tab-content">
                    <div id="original" class="tab-pane fade in active">
                        <div class="frame-box">
                            <div id="origonal">
                                <img src="<?php echo $skin_url ?>frontend/rwd/default/images/canvas_live_editor/images/original-before.jpg">
                                <img src="<?php echo $skin_url ?>frontend/rwd/default/images/canvas_live_editor/images/original-after.jpg">
                            </div>
                        </div>
                    </div>
                    <div id="sepia" class="tab-pane fade">
                        <div class="frame-box">
                            <div id="sepia-image">
                                <img src="<?php echo $skin_url ?>frontend/rwd/default/images/canvas_live_editor/images/original-before.jpg">
                                <img src="<?php echo $skin_url ?>frontend/rwd/default/images/canvas_live_editor/images/original-after.jpg">
                            </div>
                        </div>
                    </div>
                    <div id="greyscal" class="tab-pane fade">
                        <div class="frame-box">
                            <div id="greyscale">
                                <img src="<?php echo $skin_url ?>frontend/rwd/default/images/canvas_live_editor/images/original-before.jpg">
                                <img src="<?php echo $skin_url ?>frontend/rwd/default/images/canvas_live_editor/images/original-after.jpg">
                            </div>
                        </div>
                    </div>
                </div>
                <form method="post" action="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'canvas-product'; ?>">
                    <ul class="nav nav-tabs color_scale">
                        <?php $count = 1 ?>
                        <?php foreach ($product_data as $canvas_data) { ?>
                            <?php
                            if ($count <= 3) {
                                $count++;
                                continue;
                            }
                            ?>
                            <?php
                            $media_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
                            $img_url = $canvas_data['img_url'];
                            if ($canvas_data['default'] == "default") {
                                $active = $canvas_data['default'];
                            }
                            ?>
                            <li data-attr="<?php echo $canvas_data['default_title']; ?>" class="<?php echo ($active == $canvas_data['default_title']) ? "active" : ''; ?>">
                                <a data-toggle="tab" href="#<?php echo $canvas_data['canvas_type_redirect']; ?>">
                                    <img id="<?php echo $canvas_data['default_title']; ?>" src="<?php echo $media_url . $img_url ?>" alt="Thumb">
                                    <span><?php echo $canvas_data['option_label']; ?></span>

                                </a>
                                <input type="hidden" value="<?php echo $sku; ?>" name="product-sku" >
                                <input type="radio" id="color" name="color" value="<?php echo $canvas_data['default_title']; ?>" for="<?php echo $canvas_data['default_title']; ?>" />
                            </li>													
                        <?php } ?>	


                    </ul>
                    <button type="submit" class="button large border">Try Now</button>
            </div>
        </div>
    </div>

    <!-- Size & Prize -->
    <div class="size-prize padding-70" id="size-prize">
        <div class="container">
            <div class="row">
                <?php $opt_title = "Canvas Type"; ?>
                <?php $product_data = $this->getLayout()->getBlockSingleton('Canvassignages_Liveeditor_Block_Monblock')->customCanvasPrint($sku, $opt_title); ?>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <h3>Size & Prizes</h3>
                    <p>Choose the wide arrays of shapes,<br /> sizes, and patterns of your<br /> canvas style.</p>
                    <h6>Choose your type:</h6>
                    <ul class="nav nav-tabs" role="tablist">
                        <?php
                        foreach ($product_data as $canvas_data) {
                            $media_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
                            $img_url = $canvas_data['img_url'];
                            if ($canvas_data['default'] == "default") {
                                $active = $canvas_data['default_title'];
                            }
                            ?>
                            <li role="presentation" class="<?php echo ($active == $canvas_data['default_title']) ? "active" : ''; ?>">
                                <a href="#<?php echo $canvas_data['canvas_type_redirect']; ?>" role="tab" data-toggle="tab" aria-expanded="false">
                                    <img src="<?php echo $media_url . $img_url ?>" alt="Size">
                                    <img src="<?php echo $skin_url ?>frontend/rwd/default/images/canvas_live_editor/images/select-check.png" class="select-image" alt="Select Image">
                                    <span><?php echo $canvas_data['option_label']; ?></span>
                                </a>
                            </li>
                        <?php } ?>	
                    </ul>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div class="tab-content">
                        <?php
                        $j = 1;
                        foreach ($product_data as $canvas_data) {
                            $media_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
                            $img_url = $canvas_data['img_url'];
                            if ($canvas_data['default'] == "default") {
                                $active = $canvas_data['default_title'];
                            }
                            ?>									
                            <div role="tabpanel" class="tab-pane <?php echo (substr_count($active, $canvas_data['default_title']) > 0) ? 'active' : ''; ?>" id="<?php echo $canvas_data['canvas_type_redirect']; ?>">
                                <form method="post" action="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'canvas-product'; ?>">
                                    <div class="price-size-table">
                                        <ul class="list-unstyled">
                                            <li class="main-title"><h6><?php echo $canvas_type = $canvas_data['option_label']; ?></h6></li>
                                            <li class="sub-title">
                                                <span class="size-title">Select size</span>
                                                <span class="discount-title">discounted prize</span>
                                            </li>
                                            <?php
                                            $opt_title = $canvas_data['option_label'] . " Size";

                                            $opt_title_custom = $canvas_data['option_label'] . " Custom Size";
                                            $product_data = $this->getLayout()->getBlockSingleton('Canvassignages_Liveeditor_Block_Monblock')->customCanvasPrint($sku, $opt_title);

                                            $i = 0;

                                            foreach ($product_data as $canvas_data) {
                                                $media_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
                                                $img_url = $canvas_data['img_url'];

                                                $canvas_type_option_title = $canvas_data['default_title'];
                                                $canvas_type_option_label = $canvas_data['option_label'];
                                                $canvas_data_type = str_replace(" ", "_", strtolower($canvas_type_option_title));
                                                $canvas_type_redirect = str_replace(" ", "-", ($canvas_type_option_title));

                                                $default = $canvas_data['default'];
                                                $data_wh = explode('*', $canvas_type_option_title);

                                                $initial_price = $canvas_data['initial_price'];
                                                $price = number_format((float) $canvas_data['price'], 2, '.', '');
                                                $checked = 'checked="checked"';
                                                $width = $canvas_data['width'];
                                                if ($default == 'default') {
                                                    $price_default = number_format((float) $canvas_data['price'], 2, '.', '');
                                                }
                                                ?>
                                                <li>
                                                    <input id="option<?php echo $j . $i; ?>" name="selector<?php echo $j; ?>" <?php echo ($default == 'default') ? "checked" : "" ?> type="radio" value='<?php echo $canvas_type_option_label ?>' data-price="<?php echo $price; ?>">
                                                    <label for="option<?php echo $j . $i; ?>"><?php echo $canvas_type_option_label; ?>"</label>
                                                    <div class="check"></div>
                                                    <span class="price">
                                                        <?php if ($initial_price > $price) { ?>
                                                            <strike>$<?php echo $initial_price; ?></strike>
                                                        <?php } ?>
                                                        $<?php echo $price; ?>
                                                    </span>

                                                </li>
                                                <?php $i++;
                                            }
                                            ?>  							    		
                                            <li class="custom-size"> 
                                                <input id="option<?php echo $j . $i; ?>" name="selector<?php echo $j; ?>" type="radio" value="custom" data-w="Custom" >
                                                <label for="option<?php echo $j . $i; ?>">Custom Size</label>
                                                <div class="check"></div>
                                                <select name="width">
                                                    <?php
                                                    $product_data_custom = $this->getLayout()->getBlockSingleton('Canvassignages_Liveeditor_Block_Monblock')->customCanvasPrint($sku, $opt_title_custom);
                                                    print_r($product_data_custom);
                                                    foreach ($product_data_custom as $canvas_data_custom) {
                                                        $canvas_type_option_title = $canvas_data_custom['default_title'];
                                                        $data_wh = explode('*', $canvas_type_option_title);
                                                        ?>                                                   
                                                        <option value="<?php echo $data_wh[0]; ?>"><?php echo $data_wh[0]; ?></option>                                                    
    <?php } ?>                                                       
                                                </select>
                                                x
                                                <select name="height">
                                                    <?php
                                                    $product_data_custom = $this->getLayout()->getBlockSingleton('Canvassignages_Liveeditor_Block_Monblock')->customCanvasPrint($sku, $opt_title_custom);
                                                    foreach ($product_data_custom as $canvas_data_custom) {
                                                        $canvas_type_option_title = $canvas_data_custom['default_title'];
                                                        $data_wh = explode('*', $canvas_type_option_title);
                                                        ?>
                                                        <option value="<?php echo $data_wh[1]; ?>"><?php echo $data_wh[1]; ?></option>                                                       
    <?php } ?>    
                                                </select>
                                            </li>

                                            <input type="hidden" name="type" value="<?php echo $canvas_type; ?>">

                                            <input type="hidden" name="color_scale" value="<?php echo $canvas_type; ?>">
                                            <input type="hidden" value="<?php echo $sku; ?>" name="product-sku" >

                                            <li class="final-price">
                                            <strike>$37.09</strike>$6.69
                                            <button type="submit" class="button large blue start_order">Create My Canvas</button>
                                            </li>
                                        </ul>
                                    </div>
                                </form>
                            </div>
                            <?php $j++;
                        }
                        ?>						    
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Happiness Guarantee Box -->
    <?php
    $attribute = $product->getHappinessGuarentee();
    $attributeName = 'happiness_guarentee';
    echo $this->helper('catalog/output')->productAttribute($product, $attribute, $attributeName);
    ?>


    <!-- Infornmation Section -->
    <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/detail.phtml')->toHtml(); ?>
    <!-- Main Product -->
<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/related.phtml')->toHtml(); ?>


</div>

<!-- Javascript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
<script type="text/javascript" src="<?php echo $skin_url ?>frontend/revivalpixel/canvas/js/canvas_live_editor/bootstrap.js"></script>
<script type="text/javascript" src="<?php echo $skin_url ?>frontend/revivalpixel/canvas/js/canvas_live_editor/jquery-scrolltofixed.js"></script>
<script type="text/javascript" src="<?php echo $skin_url ?>frontend/revivalpixel/canvas/js/canvas_live_editor/jquery.before-after.js"></script>
<script type="text/javascript" src="<?php echo $skin_url ?>frontend/revivalpixel/canvas/js/canvas_live_editor/jquery.event.move.js"></script>


<script type="text/javascript">
    // Fixed Navigation JS
    $(document).ready(function (e) {
        $('#fix-nav').scrollToFixed();
        $('.res-nav_click').click(function () {
            $('.main-nav').slideToggle();
            return false
        });
        if ($(window).width() < 768) {
            $('.main-nav').hide();
        }

        $('.color_scale > li').click(function () {
            $('.color_scale > li #color').attr('checked', false);
            $(this).children('#color').attr('checked', 'true');
        });
    });

    // Fixed Navigation Smooth Scroll JS
    $(document).ready(function () {
        if (screen && screen.width > 991) {
            $(".main-nav li a").on('click', function (event) {
                if (this.hash !== "") {
                    event.preventDefault();
                    var hash = this.hash;
                    $('html, body').animate({
                        scrollTop: $($.attr(this, 'href')).offset().top - 68
                    }, 800, function () {
                        //window.location.hash = hash;
                    });
                }
            });
        }
        if (screen && screen.width < 992) {
            $(".main-nav li a").on('click', function (event) {
                if (this.hash !== "") {
                    event.preventDefault();
                    var hash = this.hash;
                    $('html, body').animate({
                        scrollTop: $($.attr(this, 'href')).offset().top - 150
                    }, 800, function () {
                        //window.location.hash = hash;
                    });
                }
            });
        }
        $('.main-nav li a').on('click', function () {
            $('.main-nav li a.current').removeClass('current');
            $(this).addClass('current');
            event.preventDefault();
        });
    });

    // Mobile Navigation
    $(document).ready(function () {
        var trigger = $('.hamburger'),
                overlay = $('.overlay'),
                isClosed = false;

        trigger.click(function () {
            hamburger_cross();
        });

        function hamburger_cross() {

            if (isClosed == true) {
                overlay.hide();
                trigger.removeClass('is-open');
                trigger.addClass('is-closed');
                isClosed = false;
            } else {
                overlay.show();
                trigger.removeClass('is-closed');
                trigger.addClass('is-open');
                isClosed = true;
            }
        }

        $('[data-toggle="offcanvas"]').click(function () {
            $('body').toggleClass('toggled');
        });
    });

    // Image Before After Effect JS
    $(window).on('load', function () {
        $("#origonal").twentytwenty();
        $("#sepia-image").twentytwenty();
        $("#greyscale").twentytwenty();
    });
</script>

<!-- Footer -->
<?php echo $this->getChildHtml('footer') ?>

</body>
</html>