<?php echo $this->getChildHtml('header') ?>
<?php $skin_url =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>
<link rel="stylesheet" type="text/css" href="<?php echo $skin_url?>frontend/revivalpixel/canvas/css/canvas_live_editor/before-after.css">
<div class="main-content"> 
  
  <!-- Main Banner -->
  <div class="main-banner color-black" style="background:url(<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/vector-conversion.jpg) top center no-repeat; background-size: 100%;">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
          <h3>Vector Conversion</h3>
          <p>Convert your ordinary Images, Sketches, Photo & Logos into extraordinary vectors!</p>
          <a href="#" class="button large blue">Submit your image</a> </div>
      </div>
    </div>
  </div>
  
  <!-- FIxed Navigation -->
  <nav class="main-nav-outer" id="fix-nav">
    <div class="container">
      <ul class="main-nav">
        <li><a class="current" href="#Introduction">Introduction</a></li>
        <li><a href="#Features">Features </a></li>
        <li><a href="#how-it-works">How it works</a></li>
        <li><a href="#why-choose-us">why choose us </a></li>
        <li><a href="#Samples">Samples </a></li>
        <li><a href="#plans">Plans </a></li>
        <li><a href="#convert">Convert</a></li>
      </ul>
      <a class="res-nav_click" href="#"><i class="fa fa-bars"></i></a> </div>
  </nav>
  
  <!-- Introduction -->
  <div class="padding-70" id="Introduction">
    <div class="container">
      <div class="row">
        <div class="col-lg-7 col-sm-7">
          <h3>WHat is vector conversion?</h3>
          <p>Vector Conversion service specializing in manually re-drawing images in vector format. Vector graphics are scalable suitable for large format print, screen printers, vehicle wraps, promo item printing, cut ready vector art for signs, vector line art for engraving, web use and more.</p>
          <div class="row margin-top-30">
            <div class="col-lg-6 col-sm-6 text-center"> <img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/original-img.png" class="img-responsive" alt=""/>
              <h5 class="color-grey">original image</h5>
            </div>
            <div class="col-lg-6 col-sm-6 text-center"> <img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/vactor-img.png" class="img-responsive" alt=""/>
              <h5 class="color-blue">Image converted to Vector</h5>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-5">
          <h3>WHat do we convert</h3>
          <ul class="conversion-list">
            <li>Jpg to Vector</li>
            <li>Drawing to Vector</li>
            <li>Picture to Vector</li>
            <li>Bitmap to Vector Conversion</li>
            <li>Bitmap to Vector</li>
            <li>Jpg to Vector Conversion</li>
            <li>Photo to Vector</li>
            <li>Pic to Vector</li>
            <li>Image to Vector</li>
            <li>Logo to Vector</li>
            <li>Pdf to Vector Conversion</li>
            <li>Jpeg to Vector Conversion</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  
  <!-- Features -->
  <div class="padding-70 light-grey-bg border-top-bot" id="Features">
    <div class="container ">
      <div class="row">
        <div class="col-md-6"><img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/sub-pixal.jpg" class="img-responsive" alt=""/></div>
        <div class="col-md-6">
          <h3 class="no-margin-top">Sub-pixel precision</h3>
          <p>Vector Magic carefully traces out every bit of information available in your image, slicing each edge pixel at precisely the right spot to re-create the intention of your original.<br>
            <br>
          </p>
          <p>This allows us to tease out small details that are lost by other tools, pushing the envelope of how small you can go before a nuance of your input is lost.<br>
            <br>
          </p>
          <p>Clients often give their logos in PNG format, but you may need to convert to SVG to print them. They can take hours to re-draw. Instead, use Vector Magic and you'll often get great results in just seconds. </p>
        </div>
      </div>
      <div class="row padding-top-70">
        <div class="col-md-6">
          <h3 class="no-margin-top">Manual Tracing</h3>
          <p> We don’t rely on softwares. We trace every single image manually to create pixel perfect vectors. out every bit of information available in your image, slicing each edge pixel at precisely the right spot to re-create the intention of your original.<br>
            <br>
          </p>
          <p>This allows us to tease out small details that are lost by other tools, pushing the envelope of how small you can go before a nuance of your input is lost.<br>
            <br>
          </p>
          <p>Clients often give their logos in PNG format, but you may need to convert to SVG to print them. They can take hours to re-draw. Instead, use Vector Magic and you'll often get great results in just </p>
        </div>
        <div class="col-md-6"><img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/manual-tracing.jpg" class="img-responsive" alt=""/></div>
      </div>
      <div class="row">
        <div class="col-md-6"><img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/heigest-quality.jpg" class="img-responsive" alt=""/></div>
        <div class="col-md-6">
          <h3 class="no-margin-top">Highest quality scalable vectors</h3>
          <p>Vector Magic carefully traces out every bit of information available in your image, slicing each edge pixel at precisely the right spot to re-create the intention of your original.<br>
            <br>
          </p>
          <p>This allows us to tease out small details that are lost by other tools, pushing the envelope of how small you can go before a nuance of your input is lost.<br>
            <br>
          </p>
          <p>Clients often give their logos in PNG format, but you may need to convert to SVG to print them. They can take hours to re-draw. Instead, use Vector Magic and you'll often get great results in just seconds. </p>
        </div>
      </div>
      <div class="row text-center margin-top-70"> <a href="#" class="button large blue">Submit your image</a> </div>
    </div>
  </div>
  
  <!-- How It Works -->
  <div class="vector-conversion padding-70" id="how-it-works">
    <div class="container">
      <div class="row">
        <div class="how-it-works">
          <ul>
            <li>
              <div class="number">1</div>
              <i><img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/upload.png" alt=""/></i>
              <h5>Submit</h5>
              <p>Submit low quality image</p>
            </li>
            <li>
              <div class="number">2</div>
              <i><img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/edit-icon.png" width="45" alt=""/></i>
              <h5>Redraw</h5>
              <p>We redraw the images into <br>
                vector format</p>
            </li>
            <li>
              <div class="number">3</div>
              <i><img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/preview.png" alt=""/></i>
              <h5>Preview</h5>
              <p>You will receive a preview <br>
                image of the vectorization</p>
            </li>
            <li>
              <div class="number">4</div>
              <i><img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/cart.png" alt=""/></i>
              <h5>Delivery & Payment</h5>
              <p>If you are satisfied with <br>
                preview, you make payment. </p>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  
  <!-- Why Choose Us -->
  <div class="vector-conversion padding-70" id="why-choose-us">
    <div class="container">
      <div class="row">
        <h3 class="text-center">Why choose us for vector conversion?</h3>
        <div class="margin-top-30">
          <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
            <div class="why-choose-us"> <i class="icon"><img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/dimond.png" alt=""/></i>
              <h5>HIGH QUALITY</h5>
              <p>We offer you precision hand-drawn vector conversion with maximum details, sharp lines, smooth shapes and unlimited scaling for commercial use like printers and publishers.</p>
            </div>
          </div>
          <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
            <div class="why-choose-us"> <i class="icon"><img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/pricing.png" alt=""/></i>
              <h5>PRICING</h5>
              <p>Our free online editor's intuitive controls, unlimited photo storage, and handy auto-fill feature, make it the simplest way to create gorgeous photo products.</p>
            </div>
          </div>
          <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
            <div class="why-choose-us"> <i class="icon"><img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/timing.png" alt=""/></i>
              <h5>TIMING</h5>
              <p>Whether you need design assistance or just want to check in on your order, we're standing by and ready to help. If you ever have an issue, it is easy to contact us.</p>
            </div>
          </div>
          <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
            <div class="why-choose-us"> <i class="icon"><img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/tru-vactor.png" alt=""/></i>
              <h5>True Vector</h5>
              <p>Our archival-quality eco-friendly pages feature sharp images and vibrant colors. With glossy image-wrapped hardcovers, and incredibly detailed print reproduction</p>
            </div>
          </div>
          <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
            <div class="why-choose-us"> <i class="icon"><img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/rofeshional.png" alt=""/></i>
              <h5>PROFESSIONALISM</h5>
              <p>Our archival-quality eco-friendly pages feature sharp images and vibrant colors. With glossy image-wrapped hardcovers, and incredibly detailed print reproduction</p>
            </div>
          </div>
          <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
            <div class="why-choose-us"> <i class="icon"><img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/suppots.png" alt=""/></i>
              <h5>SUPPORT</h5>
              <p>Our archival-quality eco-friendly pages feature sharp images and vibrant colors. With glossy image-wrapped hardcovers, and incredibly detailed print reproduction</p>
            </div>
          </div>
        </div>
        <p class="text-center"> <a href="#" class="button large blue margin-top-50">Submit your image</a> </p>
      </div>
    </div>
  </div>
  
  <!-- Samples -->
  <div class="padding-70 light-grey-bg border-top-bot" id="Samples">
    <div class="container ">
      <div class="row text-center">
        <h3>Vector Samples</h3>
        <p>Checkout some of samples from our previuos vector conversions</p>
        <ul class="nav nav-tabs">
          <li class="active"> <a data-toggle="tab" href="#logos"> <span>Logos</span> </a> </li>
          <li> <a data-toggle="tab" href="#jpeg"> <span>JPEG</span> </a> </li>
          <li> <a data-toggle="tab" href="#psd"> <span>PSD</span> </a> </li>
        </ul>
        <div class="tab-content">
          <div id="logos" class="tab-pane fade in active">
            <div class="frame-box">
              <div id="origonal"> <img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/logo-effects.png"> <img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/logo-effect.png"> </div>
            </div>
          </div>
          <div id="jpeg" class="tab-pane fade">
            <div class="frame-box">
              <div id="sepia-image"> <img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/original-before.jpg"> <img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/original-after.jpg"> </div>
            </div>
          </div>
          <div id="psd" class="tab-pane fade">
            <div class="frame-box">
              <div id="greyscale"> <img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/original-before.jpg"> <img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/original-after.jpg"> </div>
            </div>
          </div>
        </div>
		
      </div>
      <div class="row text-center"> <a href="#" class="button large blue">Submit your image</a> </div>
    </div>
  </div>
  <!-- Introduction -->
  <div class="padding-70" id="plans">
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-sm-4 col-xs-12">
          <div class="plans text-center">
            <div class="title orange">
              <h3>Simple</h3>
              <p>Starting at</p>
              <div class="price"><span>$</span>100</div>
            </div>
            <div class="middle-plan">
              <h5>when to choose this plan?</h5>
              <ul>
                <li> If your image is very simple </li>
                <li>If you have a digital file.</li>
                <li>If your image made out of 
                  mostly solid shapes </li>
                <li>If your image is large in size</li>
              </ul>
              <a href="#" class="button large orange">Submit your image</a> </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-4 col-xs-12">
          <div class="plans text-center">
            <div class="title blue">
              <h3>Simple</h3>
              <p>Starting at</p>
              <div class="price"><span>$</span>100</div>
            </div>
            <div class="middle-plan">
              <h5>when to choose this plan?</h5>
              <ul>
                <li> If your image is very simple </li>
                <li>If you have a digital file.</li>
                <li>If your image made out of 
                  mostly solid shapes </li>
                <li>If your image is large in size</li>
              </ul>
              <a href="#" class="button large blue">Submit your image</a> </div>
          </div>
        </div>
        <div class="col-lg-4 col-sm-4 col-xs-12">
          <div class="plans text-center">
            <div class="title green">
              <h3>Simple</h3>
              <p>Starting at</p>
              <div class="price"><span>$</span>100</div>
            </div>
            <div class="middle-plan">
              <h5>when to choose this plan?</h5>
              <ul>
                <li> If your image is very simple </li>
                <li>If you have a digital file.</li>
                <li>If your image made out of 
                  mostly solid shapes </li>
                <li>If your image is large in size</li>
              </ul>
              <a href="#" class="button large green">Submit your image</a> </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Convert -->
  <div class="padding-70 blue-bg " id="convert">
    <div class="container">
      <div class="row">
        <div class="col-lg-7 col-sm-6">
          <div class="quote">
            <h3>Ready to convert your images?</h3>
            <p class="font-18 margin-top-20">Order now for vector conversion of your images at <br>
              <u>affordable prices! </u><br>
              <br>
            </p>
            <p>We can vectorize any lower quality graphic using Adobe Illustrator, so you can use it in large size printed banner, flyers etc. If you are satisfied with our work, you can receive your vectorized image in your choice of the most common vector formats (Ai, Eps, Dwg, Svg). We can also clean up your illustration, delete backgrounds in photos and do some small changes, in order to provide you with perfectly digitalized vector images.<br>
              <br>
            </p>
            <h3>We deliver in many file types</h3>
            <div class="row software">
              <div class="col-md-2 col-sm-3 col-xs-3"><img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/ai.png" width="45" height="58" alt=""/></div>
              <div class="col-md-2 col-sm-3 col-xs-3"><img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/convert2.png" width="45" height="58" alt=""/></div>
              <div class="col-md-2 col-sm-3 col-xs-3"><img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/convert3.png" width="45" height="58" alt=""/></div>
              <div class="col-md-2 col-sm-3 col-xs-3"><img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/convert4.png" width="45" height="58" alt=""/></div>
              <div class="col-md-2 col-sm-3 col-xs-3"><img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/convert5.png" width="45" height="58" alt=""/></div>
              <div class="col-md-2 col-sm-3 col-xs-3"><img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/convert6.png" width="45" height="58" alt=""/></div>
              <div class="col-md-2 col-sm-3 col-xs-3"><img src="<?php echo $skin_url?>frontend/revivalpixel/images/canvas_live_editor/images/convert7.png" width="45" height="58" alt=""/></div>
            </div>
          </div>
        </div>
        <div class="col-lg-5 col-sm-6">
          <div class="contact-form">
            <form>
              <p>
                <input type="text" placeholder="Name">
              </p>
              <p>
                <input type="text" placeholder="Email">
              </p>
              <p>
                <input type="text" placeholder="Phone">
              </p>
              <p>
                <select placeholder=" Intended use of artwork" >
                  <option>Intended use of artwork</option>
                </select>
              </p>
              <p>
                <select placeholder=" Intended use of artwork" >
                  <option>Simple Plan (Starting @ $10)</option>
                </select>
              </p>
              <p>
              <div class="row">
                <div class="col-md-7">
                  <h5>Upload Artwork you wish 
                    to convert</h5>
                </div>
                <div class="col-md-5"><a href="#" class="button large white ">Upload</a></div>
              </div>
              </p>
              <p>
                <textarea type="text" placeholder="Comment for designer" rows="5" cols="50"></textarea>
              </p>
              <p><a href="#" class="button large border">submit your image</a></p>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Footer -->
<?php echo $this->getChildHtml('footer') ?>
<!-- Javascript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
<script type="text/javascript" src="<?php echo $skin_url?>frontend/revivalpixel/canvas/js/canvas_live_editor/bootstrap.js"></script>
<script type="text/javascript" src="<?php echo $skin_url?>frontend/revivalpixel/canvas/js/canvas_live_editor/jquery-scrolltofixed.js"></script>
<script type="text/javascript" src="<?php echo $skin_url?>frontend/revivalpixel/canvas/js/canvas_live_editor/jquery.before-after.js"></script>
<script type="text/javascript" src="<?php echo $skin_url?>frontend/revivalpixel/canvas/js/canvas_live_editor/jquery.event.move.js"></script>


<script type="text/javascript">
	
	// Fixed Navigation JS
	$(document).ready(function(e) {
        $('#fix-nav').scrollToFixed();
        $('.res-nav_click').click(function(){
            $('.main-nav').slideToggle();
            return false    
        });
        if ($(window).width() < 768 ) { 
    		$('.main-nav').hide(); 
  		}
    });
    
	// Fixed Navigation Smooth Scroll JS
	$(document).ready(function(){
		if (screen && screen.width > 991) {
			$(".main-nav li a").on('click', function(event) {
			    if (this.hash !== "") {
			      	event.preventDefault();
			      	var hash = this.hash;
			      	$('html, body').animate({
	        		scrollTop: $( $.attr(this, 'href') ).offset().top - 68
	      		}, 800, function(){
	           	//window.location.hash = hash;
	      		});
    		}
  			});
		}
		if (screen && screen.width < 992) {
			$(".main-nav li a").on('click', function(event) {
			    if (this.hash !== "") {
			      	event.preventDefault();
			      	var hash = this.hash;
			      	$('html, body').animate({
	        		scrollTop: $( $.attr(this, 'href') ).offset().top - 150
	      		}, 800, function(){
	           	//window.location.hash = hash;
	      		});
    		}
  			});
		}
	    $('.main-nav li a').on('click', function(){
		    $('.main-nav li a.current').removeClass('current');
		    $(this).addClass('current');
		    event.preventDefault();
		});
	});

	// Mobile Navigation
	$(document).ready(function () {
	  var trigger = $('.hamburger'),
	      overlay = $('.overlay'),
	     isClosed = false;

	    trigger.click(function () {
	      hamburger_cross();      
	    });

	    function hamburger_cross() {

	      if (isClosed == true) {          
	        overlay.hide();
	        trigger.removeClass('is-open');
	        trigger.addClass('is-closed');
	        isClosed = false;
	      } else {   
	        overlay.show();
	        trigger.removeClass('is-closed');
	        trigger.addClass('is-open');
	        isClosed = true;
	      }
	  }
	  
	  $('[data-toggle="offcanvas"]').click(function () {
	        $('body').toggleClass('toggled');
	  });  
	});

	// Image Before After Effect JS
	$(window).on('load', function() { 
		$("#origonal").twentytwenty();
	  	$("#sepia-image").twentytwenty();
	  	$("#greyscale").twentytwenty();
	});
	
	// Panel Display Filter 
	$(document).ready(function(){
		$(".filter-button").click(function(){
        	var value = $(this).attr('data-filter');
        	if(value == "all")
        		{
            	$('.panel-display-box').show('3000');
        		}
        	else
        	{
            	$(".panel-display-box").not('.'+value).hide('3000');
            	$('.panel-display-box').filter('.'+value).show('3000');
        	}
    	
    	if ($(".filter-button").removeClass("active")) {
			$(this).removeClass("active");
		}
		$(this).addClass("active");
		});
		});
	</script>
</body>
</html>