<?php
/*
* Template For Showing The Metal Content
*/

?>

 <?php 
 $sku = "fancy-halo-flip-ring";
 $opt_title = "Metal";
 $product_data = $this->getLayout()->getBlockSingleton('Canvassignages_Liveeditor_Block_Monblock')->customCanvasPrint($sku,$opt_title);

 //print_r($product_data);
  ?>
  <div class="panel panel-default sku_pane">
                                        <!-- Metal Pane Header -->
                                        <div class="panel-heading clearfix" data-toggle="collapse" data-parent="" href=".skuCollapse">
                                            <div class="mw-thumb mw-thumb-metal"> 


                                            <img width="40" height="40" class="sku_thumb summary_thumb summary_thumb_metal lazyloaded" src="./JWELZHQ_files/jewlr-4a34acfad1ff8388b748c3eb253a6fbb5b3e4fbe9a34cbeaf169de003c69853b.gif" alt="Jewlr" srcset="https://j4-assets-jewlr.netdna-ssl.com/assets/product/sku/1x/SS-9d06a9f9a8ec033f4cfb8428e39c35ba071842750726f221f2404792cd898767.png 1x, https://j4-assets-jewlr.netdna-ssl.com/assets/product/sku/2x/SS-e51eee7e95e743843f3e9cbea865b6995749c6dcdd422d5d1e0c60542284feb4.png 2x"> </div>
                                            <div class="mw-desc">
                                                <h4>Metal</h4>
                                                <span class="sku_description sku_description_metal">Sterling Silver</span> </div>
                                            <div class="mw-chevron"> <span class="fa fa-angle-right"></span> </div>
                                            <div class="mw-price"> <span class="sku_price">$109</span> </div>
                                        </div>


                       <div class="panel-collapse collapse skuCollapse">
                                            <div class="panel-body">
                                                <div class="wizard-pane sku_pane item" data-maparea="shank" data-summary-field="sku" data-pref="sku" data-hashid="sku" data-label="Metal">
                                                    
                                                    <!-- end div pane-title -->
                                                    <div class="pane-content clearfix">
                                                        <div class="wizard-option-category">
                                                            <ul class="thumbnails list-unstyled list-inline">

                                                           

                                                            </ul>
                                                        </div>
                                                    </div>
                                                    <!-- HOLIDAY GUARANTEE FOR METAL -->
                                                    <div id="metal-guarantee" class="clearfix">
                                                        <div class="guarantee-icon-container pull-left"></div>
                                                        <div class="guarantee-text-container"></div>
                                                    </div>
                                                    <div id="metal-guarantee-details">
                                                        <div class="guarantee-details-container"></div>
                                                    </div>
                                                    <!-- END HOLIDAY GUARANTEE FOR METAL -->
                                                    <!-- end div pane-content -->
                                                </div>
                                            </div>
                                        </div>
                                </div>        

