<div class="accordianheader">
    <div class="acr_details">
      <img src=""/>
       <div class="des">
          <h3> Size</h3>
          <div class="label_des">14K Yellow Gold</div>
        </div>
        <div class="prc">
          $389     <i class="fa fa-angle-down"></i>
        </div>
    </div>
                                  
 </div>
<div class="accordianbody">
   <ul>
      <li><p>The average ring size for women is size 7.00.
             If you are unsure of the size, read our Ring Sizing Tips.
             We offer one FREE resizing (within 2 full sizes) of your ring within 30 days.</p></li>
      <li>
         <select>
            <?php 
             $sku = "fancy-halo-flip-ring";
             $opt_title = "RING SIZE";
             $product_data = $this->getLayout()->getBlockSingleton('Canvassignages_Liveeditor_Block_Monblock')->customCanvasPrint($sku,$opt_title);
              ?>
              <?php foreach($product_data as $dimond_data) {?>

                  <option><?php echo $dimond_data['default_title']; ?></option>>

              <?php } ?>
         </select>
      </li>       

   </ul>
</div>
