<div class="accordianheader">
    <div class="acr_details">
      <img src=""/>
       <div class="des">
          <h3> Side 2 Stone 1</h3>
          <div class="label_des">14K Yellow Gold</div>
        </div>
        <div class="prc">
          $389     <i class="fa fa-angle-down"></i>
        </div>
    </div>
                                  
 </div>
<div class="accordianbody">
   <ul>
          <li>
            Provides vouchers that allow residents to enter private rental market.</li>
          <li>
            Requires residents to live in areas less than 10% poor</li>
          
   </ul>
 
</div>
