<?php $skin_url =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>
<a href="#" class="link">
                            <img src="<?php echo $skin_url?>frontend/rwd/default/images/canvas_live_editor/images/text.png" alt="Editor Icon">
                            <span>Text</span>
                        </a>
                        <div class="sidebar-content text">
                            <div class="form-group">
                                <label for="comment">Add Text</label>
                                <textarea class="form-control" rows="4" id="comment" placeholder="Type Here"></textarea>
                                <button class="button medium blue">Add</button>
                            </div>
                        </div>
