<?php $skin_url =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN);?>
<a href="#" class="link">
                            <img src="<?php echo $skin_url?>frontend/rwd/default/images/canvas_live_editor/images/image.png" alt="Editor Icon">
                            <span>Image</span>
                        </a>
                        <div class="sidebar-content image">
                            <button type="button" class="button medium blue" data-toggle="modal" data-target="#photo-uplopad">
                                Upload Photos
                            </button>
                            <div class="upload-photo-icon">
                                <img src="<?php echo $skin_url?>frontend/rwd/default/images/canvas_live_editor/images/upload-photo-icon.png" alt="upload photo icon">
                            </div>
                            <div class="uploaded-image">
                                <!-- <div class="uploaded-photo-box">
                                    <img src="<?php echo $skin_url?>frontend/rwd/default/images/canvas_live_editor/images/remove-white.png" class="remove" alt="Remove">
                                    <img src="<?php echo $skin_url?>frontend/rwd/default/images/canvas_live_editor/images/select-check.png" class="select-check" alt="Select Check">
                                    <img src="<?php echo $skin_url?>frontend/rwd/default/images/canvas_live_editor/images/img_test.jpg" alt="My Photos">
                                </div>
                                <div class="uploaded-photo-box">
                                    <img src="<?php echo $skin_url?>frontend/rwd/default/images/canvas_live_editor/images/remove-white.png" class="remove" alt="Remove">
                                    <img src="<?php echo $skin_url?>frontend/rwd/default/images/canvas_live_editor/images/select-check.png" class="select-check" alt="Select Check">
                                    <img src="<?php echo $skin_url?>frontend/rwd/default/images/canvas_live_editor/images/Kayla_Person-small.jpg" alt="My Photos">
                                </div>
                                <div class="uploaded-photo-box">
                                    <img src="<?php echo $skin_url?>frontend/rwd/default/images/canvas_live_editor/images/remove-white.png" class="remove" alt="Remove">
                                    <img src="<?php echo $skin_url?>frontend/rwd/default/images/canvas_live_editor/images/select-check.png" class="select-check" alt="Select Check">
                                    <img src="<?php echo $skin_url?>frontend/rwd/default/images/canvas_live_editor/images/my-photos-image.jpg" alt="My Photos">
                                </div>
                                <div class="uploaded-photo-box">
                                    <img src="<?php echo $skin_url?>frontend/rwd/default/images/canvas_live_editor/images/remove-white.png" class="remove" alt="Remove">
                                    <img src="<?php echo $skin_url?>frontend/rwd/default/images/canvas_live_editor/images/select-check.png" class="select-check" alt="Select Check">
                                    <img src="<?php echo $skin_url?>frontend/rwd/default/images/canvas_live_editor/images/banner_img2.jpg" alt="My Photos">
                                </div> -->
                               
                                
                            </div>
                        </div>
